/* auto-generated by NAPI-RS - manually maintained for history module */
/* eslint-disable */

// ============================================================================
// History Module Types
// ============================================================================

/** Handle to a HistoryStore */
export declare class HistoryStoreHandle {
  createEditRecord(projectId: string, input: CreateEditRecordInput): NapiEditRecord
  getEditRecord(projectId: string, id: string): NapiEditRecord | null
  getRecentEdits(projectId: string, limit?: number): NapiEditRecord[]
  getEditsBySession(projectId: string, sessionId: string): NapiEditRecord[]
  getEditsByFile(projectId: string, filePath: string): NapiEditRecord[]
  startEditSession(projectId: string, description?: string): NapiEditSession
  getEditSession(projectId: string, id: string): NapiEditSession | null
  endEditSession(projectId: string, id: string): NapiEditSession | null
  getAllSessions(projectId: string): NapiEditSession[]
  getActiveSessions(projectId: string): NapiEditSession[]
  createDecision(projectId: string, input: CreateDecisionInput): NapiDecisionRecord
  getDecision(projectId: string, id: string): NapiDecisionRecord | null
  getRecentDecisions(projectId: string, limit?: number): NapiDecisionRecord[]
  getDecisionsByType(projectId: string, decisionType: string): NapiDecisionRecord[]
  searchDecisions(projectId: string, query: string): NapiDecisionRecord[]
  deleteDecision(projectId: string, id: string): boolean
  createAdr(projectId: string, input: CreateAdrInput): NapiAdr
  getAdr(projectId: string, id: string): NapiAdr | null
  getAllAdrs(projectId: string): NapiAdr[]
  formatAdrMarkdown(projectId: string, id: string): string | null
  getEditStats(projectId: string): NapiEditStats
  cleanup(projectId: string, beforeTimestamp: number): number
  invalidate(projectId: string): void
}

export declare function openHistoryStore(path: string): HistoryStoreHandle
export declare function createMemoryHistoryStore(): HistoryStoreHandle

export interface NapiFileEdit {
  path: string
  type: string
  additions: number
  deletions: number
  preHash?: string
  postHash?: string
}

export interface NapiEditRecord {
  id: string
  sessionId?: string
  timestamp: number
  description?: string
  edits: NapiFileEdit[]
  agent?: string
  model?: string
  tokensUsed?: number
  duration?: number
}

export interface CreateEditRecordInput {
  edits: NapiFileEdit[]
  sessionId?: string
  description?: string
  agent?: string
  model?: string
  tokensUsed?: number
  duration?: number
}

export interface NapiEditSession {
  id: string
  projectId: string
  startTime: number
  endTime?: number
  edits: string[]
  totalTokens: number
  totalDuration: number
  description?: string
}

export interface NapiDecisionRecord {
  id: string
  type: string
  title: string
  description: string
  rationale?: string
  alternatives?: string[]
  outcome?: string
  sessionId?: string
  files?: string[]
  tags?: string[]
  timestamp: number
}

export interface CreateDecisionInput {
  type: string
  title: string
  description: string
  rationale?: string
  alternatives?: string[]
  outcome?: string
  sessionId?: string
  files?: string[]
  tags?: string[]
}

export interface NapiAlternative {
  description: string
  rejected: boolean
  reason?: string
}

export interface NapiAdr {
  id: string
  title: string
  status: string
  context: string
  decision: string
  consequences: string[]
  alternatives?: NapiAlternative[]
  supersededBy?: string
  created: number
  updated: number
  tags?: string[]
}

export interface CreateAdrInput {
  title: string
  context: string
  decision: string
  consequences: string[]
  status?: string
  alternatives?: NapiAlternative[]
  tags?: string[]
}

export interface NapiAgentStats {
  name: string
  editCount: number
  tokenCount: number
}

export interface NapiFileEditCount {
  path: string
  count: number
}

export interface NapiEditStats {
  totalEdits: number
  totalAdditions: number
  totalDeletions: number
  totalFiles: number
  topFiles: NapiFileEditCount[]
  agentStats: NapiAgentStats[]
}

// ============================================================================
// Session Module Types
// ============================================================================

export declare class SessionStoreHandle {
  save(session: NapiSessionData): void
  load(id: string): NapiSessionData | null
  list(): NapiSessionData[]
  delete(id: string): boolean
}

export declare function openSessionStore(path: string): SessionStoreHandle

export interface NapiMessage {
  id: string
  role: string
  content: string
  timestamp: string
  tokens?: number
  toolCallId?: string
  toolName?: string
  compacted: boolean
}

export interface NapiSessionData {
  id: string
  name?: string
  cwd: string
  createdAt: string
  updatedAt: string
  messages: NapiMessage[]
}

// ============================================================================
// Audit Module Types
// ============================================================================

export declare class NapiAuditLog {
  constructor()
  log(entry: NapiAuditEntryInput): Promise<string>
  query(filter: NapiAuditFilter): Promise<NapiAuditEntry[]>
  exportReport(sessionId: string): Promise<NapiAuditReport>
  count(filter?: NapiAuditFilter): Promise<number>
  clear(): Promise<void>
}

export interface NapiAuditEntryInput {
  sessionId: string
  entryType: NapiAuditEntryType
  action: string
  input: string
  result: NapiAuditResult
  risk?: NapiRiskLevel
  autoApproved?: boolean
  reason: string
  metadata: string
}

export interface NapiAuditEntry {
  id: string
  timestamp: number
  sessionId: string
  entryType: NapiAuditEntryType
  action: string
  input: string
  result: NapiAuditResult
  risk?: NapiRiskLevel
  autoApproved?: boolean
  reason: string
  metadata: string
}

export interface NapiAuditFilter {
  sessionId?: string
  entryType?: NapiAuditEntryType
  result?: NapiAuditResult
  risk?: NapiRiskLevel
  autoApproved?: boolean
  fromTimestamp?: number
  toTimestamp?: number
  action?: string
  limit?: number
  offset?: number
}

export interface NapiAuditReport {
  sessionId: string
  generatedAt: string
  summary: NapiAuditSummary
  entries: NapiAuditEntry[]
}

export interface NapiAuditSummary {
  totalEntries: number
  byType: any
  byResult: any
  byRisk: any
  autoApprovedCount: number
  timeRange: any
}

export declare const enum NapiAuditEntryType {
  Permission = 'Permission',
  ToolCall = 'ToolCall',
  Decision = 'Decision',
  StateChange = 'StateChange',
  Checkpoint = 'Checkpoint',
  Rollback = 'Rollback',
  Error = 'Error',
  SessionStart = 'SessionStart',
  SessionEnd = 'SessionEnd'
}

export declare const enum NapiAuditResult {
  Approved = 'Approved',
  Rejected = 'Rejected',
  Error = 'Error',
  Success = 'Success',
  Failed = 'Failed'
}

export declare const enum NapiRiskLevel {
  Safe = 'Safe',
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical'
}

// ============================================================================
// Security Module Types
// ============================================================================

export declare class PermissionManagerHandle {
  addRule(rule: NapiPermissionRule): void
  grant(permission: NapiPermission): void
  check(permission: NapiPermission): boolean
  clear(): void
}

export declare function createPermissionManager(): PermissionManagerHandle

export interface NapiPermission {
  tool: string
  action: string
  resource?: string
}

export interface NapiPermissionRule {
  permission: NapiPermission
  allow: boolean
  reason?: string
}

export declare class VaultHandle {
  set(entry: NapiSecretEntry): void
  get(name: string): NapiSecretEntry | null
  getValue(name: string): string | null
  delete(name: string): boolean
  list(): string[]
  save(): void
}

export declare function openVault(path: string, password: string): VaultHandle
export declare function createMemoryVault(password: string): VaultHandle

export interface NapiSecretEntry {
  name: string
  value: string
  description?: string
}

export declare class InjectionScannerHandle {
  scan(input: string): InjectionScanResult
  quickCheck(input: string): boolean
  sanitize(input: string): string
}

export declare function createInjectionScanner(): InjectionScannerHandle
export declare function scanInjection(input: string): InjectionScanResult
export declare function quickCheckInjection(input: string): boolean
export declare function sanitizeInjectionInput(input: string): string

export interface InjectionScanResult {
  detected: boolean
  confidence: number
  patterns: InjectionPattern[]
  sanitized?: string
  durationMs: number
}

export interface InjectionPattern {
  injectionType: string
  matched: string
  position: number
  severity: string
  description: string
}

// ============================================================================
// Context Module Types
// ============================================================================

export declare function scoreRelevance(query: string, content: string): NapiRelevanceScore
export declare function scoreFiles(query: string, files: NapiFileMetadata[]): NapiScoredFile[]

export interface NapiRelevanceScore {
  score: number
  keywordScore: number
  structuralScore: number
  recencyScore: number
  matchedKeywords: string[]
}

export interface NapiFileMetadata {
  path: string
  content: string
  modified?: number
  extension?: string
}

export interface NapiScoredFile {
  path: string
  score: NapiRelevanceScore
}

// ============================================================================
// PTY Module Types
// ============================================================================

export declare class LspServerManagerHandle {
  startForFile(filePath: string): Promise<string>
  start(serverId: string, root: string): Promise<string>
  request(key: string, method: string, params: any): Promise<any>
  stop(key: string): Promise<void>
  status(key: string): Promise<LspServerStatus>
  allStatuses(): Promise<Record<string, LspServerStatus>>
  stopAll(): Promise<void>
}

export declare function createLspServerManager(): LspServerManagerHandle

export interface LspServerStatus {
  status: string
  error?: string
}

// ============================================================================
// Storage Module Types
// ============================================================================

export declare class KvStoreHandle {
  set(key: string[], value: string): Promise<void>
  get(key: string[]): Promise<string | null>
  delete(key: string[]): Promise<boolean>
  exists(key: string[]): Promise<boolean>
  list(prefix: string[]): Promise<string[]>
  count(prefix: string[]): Promise<number>
  deletePrefix(prefix: string[]): Promise<number>
  stats(): Promise<NapiStoreStats>
  healthCheck(): Promise<boolean>
  compact(): Promise<void>
  path(): string
}

export type KVStoreHandle = KvStoreHandle

export declare function openKvStore(path: string): Promise<KvStoreHandle>
export declare function createMemoryKvStore(): KvStoreHandle

export interface NapiStoreStats {
  totalEntries: number
  totalSizeBytes: number
  oldestEntryMs?: number
  newestEntryMs?: number
}

// ============================================================================
// Shell Parser Types
// ============================================================================

export declare class ShellParserHandle {
  parse(command: string): any
  assessRisk(commands: string[]): any
  extractDirectories(command: string): string[]
  extractPermissionPatterns(command: string): any[]
}

export declare function parseShellCommand(command: string): any
export declare function assessShellCommandsRisk(commands: string[]): any
export declare function extractShellDirectories(command: string): string[]
export declare function extractShellPermissionPatterns(command: string): any[]
export declare function isFileCommand(command: string): boolean
export declare function isDangerousCommand(command: string): boolean

// ============================================================================
// Risk Assessment Types
// ============================================================================

export declare function assessBashRisk(command: string): any
export declare function assessFileRisk(path: string): any
export declare function getToolBaseRisk(tool: string): any
export declare function checkRiskThreshold(risk: any, threshold: any): boolean
export declare function parseRiskLevel(level: string): any

// ============================================================================
// Autonomous State Types
// ============================================================================

export declare const AutonomousState: any
export declare const StateCategory: any
export declare const TaskPriority: any
export declare const TaskStatus: any

export declare class StateMachineHandle {
  transition(event: any): any
  currentState(): any
  history(): any[]
}

export declare function createStateMachine(config: any): StateMachineHandle

export declare class TaskQueueHandle {
  enqueue(task: any): string
  dequeue(): any
  peek(): any
  remove(id: string): boolean
  list(): any[]
  clear(): void
}

export declare function createTaskQueue(): TaskQueueHandle

// ============================================================================
// Provider Transform Types
// ============================================================================

export declare function normalizeMessages(messages: any[]): any[]
export declare function applyCaching(messages: any[]): any[]
export declare function remapProviderOptions(options: any): any
export declare function getSdkKey(provider: string): string
export declare function getTemperature(provider: string): number
export declare function getTopP(provider: string): number
export declare function getTopK(provider: string): number
export declare function transformMessages(provider: string, messages: any[]): any[]

// ============================================================================
// Message Store Types
// ============================================================================

export declare class MessageStoreHandle {
  push(message: NapiMessage): void
  messages(): NapiMessage[]
  lastN(n: number): NapiMessage[]
  totalTokens(): number
  len(): number
  isEmpty(): boolean
  add(message: any): void
  get(id: string): any
  list(): any[]
  delete(id: string): boolean
  clear(): void
}

export declare function createMessageStore(): MessageStoreHandle
export declare const MessageRole: any

// ============================================================================
// Injection Scanner Extended Types
// ============================================================================

export declare function createInjectionScannerWithConfig(config: any): InjectionScannerHandle
export declare function scanInjectionWithConfig(input: string, config: any): InjectionScanResult
export declare const InjectionSeverity: any
export declare const InjectionType: any

// ============================================================================
// Context Extended Types
// ============================================================================

export declare function scoreRelevanceWithConfig(query: string, content: string, config: any): NapiRelevanceScore

// ============================================================================
// Graph Module Types
// ============================================================================

export declare class CallGraphHandle {
  addCall(caller: string, callee: string): void
  getCallers(fn: string): string[]
  getCallees(fn: string): string[]
  clear(): void
}

export declare class CausalGraphHandle {
  addCause(effect: string, cause: string): void
  getCauses(effect: string): string[]
  getEffects(cause: string): string[]
  clear(): void
}

export declare class GraphEngineHandle {
  addNode(id: string, data: any): void
  addEdge(from: string, to: string, data: any): void
  getNode(id: string): any
  getNeighbors(id: string): string[]
  clear(): void
}

export declare class SemanticGraphHandle {
  addConcept(id: string, data: any): void
  addRelation(from: string, to: string, relation: string): void
  getRelated(id: string, relation?: string): string[]
  clear(): void
}

// ============================================================================
// Fingerprint Module Types
// ============================================================================

export declare class FingerprintEngineHandle {
  generate(content: string): any
  compare(a: any, b: any): number
}

export declare function generateFingerprint(content: string): any
export declare function fingerprintSimilarity(a: any, b: any): number
export declare function describeFingerprint(fp: any): string
export declare function contentHash(content: string): string

// ============================================================================
// Web Fingerprint Types
// ============================================================================

export declare class WebFingerprintEngineHandle {
  detect(html: string): any[]
  getCategories(): string[]
  getFingerprints(category?: string): any[]
}

export declare function detectWebTechnologies(html: string): any[]
export declare function getWebCategories(): string[]
export declare function getWebFingerprints(): any[]
export declare function getWebFingerprintsByCategory(category: string): any[]

// ============================================================================
// Java Analysis Types
// ============================================================================

export declare class JarAnalyzerHandle {
  analyze(path: string): any
  getSummary(): any
}

export declare function analyzeJar(path: string): any
export declare function jarAnalysisSummary(analysis: any): string
export declare function detectJavaTechnologies(analysis: any): any[]
export declare function parseClassFileSync(path: string): any

// ============================================================================
// Credential & Keyring Types
// ============================================================================

export declare class CredentialManagerHandle {
  set(name: string, value: string): void
  get(name: string): string | null
  delete(name: string): boolean
  list(): string[]
}

export declare class KeyringManagerHandle {
  set(service: string, account: string, password: string): void
  get(service: string, account: string): string | null
  delete(service: string, account: string): boolean
}

export declare function createCredentialManager(): CredentialManagerHandle
export declare function createFileCredentialManager(path: string): CredentialManagerHandle
export declare function createKeyringManager(): KeyringManagerHandle
export declare function createFileKeyringManager(path: string): KeyringManagerHandle
export declare function isKeyringAvailable(): boolean
export declare const CredentialType: any
export declare const KeyringBackend: any

// ============================================================================
// MCP Types
// ============================================================================

export declare class McpAuthStoreHandle {
  set(server: string, token: string): void
  get(server: string): string | null
  delete(server: string): boolean
  list(): string[]
}

export declare class McpClientManagerHandle {
  connect(url: string, config?: any): Promise<void>
  disconnect(url: string): Promise<void>
  call(url: string, method: string, params: any): Promise<any>
  listConnections(): string[]
}

export declare function createMcpAuthStore(): McpAuthStoreHandle
export declare function createFileMcpAuthStore(path: string): McpAuthStoreHandle
export declare function createMcpClientManager(): McpClientManagerHandle
export declare const McpTransportType: any

// ============================================================================
// Trace Types
// ============================================================================

export declare class TraceStoreHandle {
  record(trace: any): void
  query(filter: any): any[]
  clear(): void
}

export declare function openTraceStore(path: string): TraceStoreHandle
export declare function createMemoryTraceStore(): TraceStoreHandle

// ============================================================================
// Editor & Patch Types
// ============================================================================

export declare class EditorHandle {
  open(path: string): void
  edit(operation: any): void
  save(): void
  close(): void
}

export declare class PatchApplicatorHandle {
  apply(patch: any): any
  revert(patch: any): any
}

export declare function editFile(path: string, operation: any): any
export declare function computeDiff(a: string, b: string): any
export declare function replaceWithFuzzyMatch(content: string, search: string, replace: string): any
export declare function findBestMatch(content: string, pattern: string): any
export declare function readFile(path: string): string
export declare const NapiPatchType: any

// ============================================================================
// Utility Functions
// ============================================================================

export declare function glob(pattern: string, options?: any): string[]
export declare function grep(pattern: string, path: string, options?: any): any[]
export declare function bytesToVector(bytes: Uint8Array): number[]
export declare function vectorToBytes(vector: number[]): Uint8Array
export declare function normalizeVector(vector: number[]): number[]
export declare function cosineSimilarity(a: number[], b: number[]): number
export declare function vectorDistance(a: number[], b: number[]): number
export declare function hybridMergeResults(results: any[], config?: any): any[]
export declare function chunkText(text: string): string[]
export declare function chunkTextWithConfig(text: string, config: any): string[]
export declare function estimateTokens(text: string): number
export declare function levenshteinDistance(a: string, b: string): number
export declare function similarityRatio(a: string, b: string): number

// ============================================================================
// Project Detection Types
// ============================================================================

export declare const NapiFrameworkType: any
export declare const NapiPackageManager: any
export declare const NapiProjectLanguage: any

// ============================================================================
// Other Common Types
// ============================================================================

export declare function version(): string
export declare function init(): void

// ============================================================================
// Git Operations Types (Phase 8.1)
// ============================================================================

export interface NapiGitStatus {
  modified: string[]
  added: string[]
  deleted: string[]
  renamed: Record<string, string>
  untracked: string[]
  branch: string
  ahead: number
  behind: number
  files: NapiFileStatus[]
}

export interface NapiFileStatus {
  path: string
  status: string
  staged: boolean
  oldPath?: string
}

export interface NapiCommitResult {
  success: boolean
  commitHash?: string
  error?: string
}

export interface NapiCommitInfo {
  hash: string
  message: string
  author: string
  date: number
}

export interface NapiDiffFile {
  path: string
  status: string
  additions: number
  deletions: number
  patch?: string
}

export interface NapiDiffResult {
  files: NapiDiffFile[]
  insertions: number
  deletions: number
  filesChanged: number
}

export interface NapiOperationResult {
  success: boolean
  error?: string
}

export interface NapiInitOptions {
  defaultBranch?: string
  initialCommit?: boolean
  commitMessage?: string
}

export interface NapiCloneOptions {
  depth?: number
  branch?: string
  reinitialize?: boolean
}

export interface NapiWorktreeInfo {
  /** The name of the worktree (used to identify it in git) */
  name: string
  /** The filesystem path to the worktree */
  path: string
  /** The branch checked out in the worktree */
  branch: string
  /** Whether the worktree is locked */
  locked: boolean
  /** Whether the worktree is prunable (invalid/missing) */
  prunable: boolean
}

export declare class GitOpsHandle {
  path(): string
  status(): NapiGitStatus
  currentBranch(): string
  isClean(): boolean
  commit(message: string, addAll?: boolean, allowEmpty?: boolean): NapiCommitResult
  commits(limit?: number): NapiCommitInfo[]
  currentCommit(): string | null
  reset(commitHash: string, hard?: boolean): NapiOperationResult
  diff(from?: string, to?: string): NapiDiffResult
  changedFiles(sinceCommit?: string): string[]
  stash(message?: string): NapiOperationResult
  stashPop(): NapiOperationResult
  stashList(): string[]
  addRemote(name: string, url: string): NapiOperationResult
  removeRemote(name: string): NapiOperationResult
  remoteUrl(name: string): string | null
  remotes(): string[]
  fetch(remote?: string): NapiOperationResult
  push(remote?: string, branch?: string, setUpstream?: boolean): NapiOperationResult
  createBranch(name: string, from?: string): NapiOperationResult
  checkout(refName: string): NapiOperationResult
  deleteBranch(name: string, force?: boolean): NapiOperationResult
  branches(includeRemote?: boolean): string[]
  stageFiles(paths: string[]): NapiOperationResult
  unstageFiles(paths: string[]): NapiOperationResult
  // Worktree operations
  listWorktrees(): NapiWorktreeInfo[]
  addWorktree(name: string, path: string, branch?: string): NapiWorktreeInfo
  removeWorktree(name: string, force?: boolean): NapiOperationResult
  pruneWorktrees(): NapiOperationResult
  lockWorktree(name: string, reason?: string): NapiOperationResult
  unlockWorktree(name: string): NapiOperationResult
  getWorktree(name: string): NapiWorktreeInfo | null
  refExists(refName: string): boolean
}

export declare function openGitRepo(path: string): GitOpsHandle
export declare function initGitRepo(path: string, options?: NapiInitOptions): GitOpsHandle
export declare function cloneGitRepo(url: string, path: string, options?: NapiCloneOptions): GitOpsHandle
export declare function isGitRepo(path: string): boolean

// ============================================================================
// Markdown Module Types (Phase 11)
// ============================================================================

export interface NapiMarkdownHeading {
  /** Heading level (1-6) */
  level: number
  /** Heading text content */
  text: string
  /** Line number in source (1-indexed) */
  line: number
}

export interface NapiMarkdownCodeBlock {
  /** Language identifier (e.g., "rust", "python") */
  language: string | null
  /** Code content */
  code: string
  /** Start line in source (1-indexed) */
  startLine: number
  /** End line in source (1-indexed) */
  endLine: number
}

export interface NapiMarkdownLink {
  /** URL destination */
  url: string
  /** Link text */
  text: string
  /** Optional title attribute */
  title: string | null
  /** Line number in source (1-indexed) */
  line: number
}

export interface NapiMarkdownImage {
  /** Image URL/path */
  url: string
  /** Alt text */
  alt: string
  /** Optional title attribute */
  title: string | null
  /** Line number in source (1-indexed) */
  line: number
}

export interface NapiMarkdownNode {
  /**
   * Node type: "heading", "paragraph", "code_block", "inline_code", "list",
   * "block_quote", "link", "image", "horizontal_rule", "table", "html",
   * "task_list_item", "footnote_definition"
   */
  nodeType: string
  /** JSON-serialized content (structure depends on nodeType) */
  content: string
}

/** Parse markdown text into a vector of typed nodes */
export declare function parseMarkdown(text: string): NapiMarkdownNode[]

/** Extract all headings from markdown text */
export declare function extractMarkdownHeadings(text: string): NapiMarkdownHeading[]

/** Extract all fenced and indented code blocks from markdown text */
export declare function extractMarkdownCodeBlocks(text: string): NapiMarkdownCodeBlock[]

/** Extract all links from markdown text */
export declare function extractMarkdownLinks(text: string): NapiMarkdownLink[]

/** Extract all images from markdown text */
export declare function extractMarkdownImages(text: string): NapiMarkdownImage[]

/** Render markdown text to HTML */
export declare function renderMarkdownToHtml(text: string): string

/** Extract frontmatter from markdown text (YAML between --- delimiters) */
export declare function extractMarkdownFrontmatter(text: string): string | null

/** Remove frontmatter from markdown text */
export declare function stripMarkdownFrontmatter(text: string): string

// ============================================================================
// PTY Module Types (Phase 12)
// ============================================================================

export interface NapiPtyConfig {
  /** Initial terminal width in columns */
  cols?: number
  /** Initial terminal height in rows */
  rows?: number
  /** Shell to use */
  shell?: string
  /** Working directory */
  cwd?: string
  /** Environment variables */
  env?: Record<string, string>
  /** Inherit environment from parent */
  inheritEnv?: boolean
}

export declare const enum NapiPtyState {
  Running = 'Running',
  Exited = 'Exited',
  Killed = 'Killed',
  Error = 'Error'
}

export interface NapiPtyInfo {
  /** Session ID */
  id: string
  /** Current state */
  state: NapiPtyState
  /** Exit code (if exited) */
  exitCode: number | null
  /** Terminal width */
  cols: number
  /** Terminal height */
  rows: number
  /** Shell being used */
  shell: string
  /** Working directory */
  cwd: string
}

export declare class PtySessionHandle {
  /** Get the session ID */
  readonly id: string
  /** Check if the session is running */
  isRunning(): boolean
  /** Get session info */
  info(): NapiPtyInfo
  /** Read output from the PTY (non-blocking) */
  read(): Buffer
  /** Read output with timeout (milliseconds) */
  readWithTimeout(timeoutMs: number): Buffer
  /** Write data to the PTY */
  write(data: Buffer): void
  /** Write a line (with newline) to the PTY */
  writeLine(line: string): void
  /** Resize the terminal */
  resize(cols: number, rows: number): void
  /** Kill the process */
  kill(): void
  /** Wait for the process to exit */
  wait(): number
  /** Wait for the process with timeout (milliseconds) */
  waitWithTimeout(timeoutMs: number): number | null
  /** Get exit code (if exited) */
  exitCode(): number | null
}

export declare class PtyManagerHandle {
  constructor()
  /** Create a new shell session */
  create(config: NapiPtyConfig): string
  /** Create a new session with a specific command */
  createCommand(command: string, args: string[], config: NapiPtyConfig): string
  /** List all session IDs */
  list(): string[]
  /** List all session info */
  listInfo(): NapiPtyInfo[]
  /** Clean up exited sessions */
  cleanup(): void
  /** Kill all sessions */
  killAll(): void
}

/** Spawn a new PTY session */
export declare function spawnPty(config: NapiPtyConfig): PtySessionHandle

/** Spawn a new PTY session with a specific command */
export declare function spawnPtyCommand(command: string, args: string[], config: NapiPtyConfig): PtySessionHandle
