/* auto-generated by NAPI-RS - manually maintained for history module */
/* eslint-disable */

// ============================================================================
// History Module Types
// ============================================================================

/** Handle to a HistoryStore */
export declare class HistoryStoreHandle {
  createEditRecord(projectId: string, input: CreateEditRecordInput): NapiEditRecord
  getEditRecord(projectId: string, id: string): NapiEditRecord | null
  getRecentEdits(projectId: string, limit?: number): NapiEditRecord[]
  getEditsBySession(projectId: string, sessionId: string): NapiEditRecord[]
  getEditsByFile(projectId: string, filePath: string): NapiEditRecord[]
  startEditSession(projectId: string, description?: string): NapiEditSession
  getEditSession(projectId: string, id: string): NapiEditSession | null
  endEditSession(projectId: string, id: string): NapiEditSession | null
  getAllSessions(projectId: string): NapiEditSession[]
  getActiveSessions(projectId: string): NapiEditSession[]
  createDecision(projectId: string, input: CreateDecisionInput): NapiDecisionRecord
  getDecision(projectId: string, id: string): NapiDecisionRecord | null
  getRecentDecisions(projectId: string, limit?: number): NapiDecisionRecord[]
  getDecisionsByType(projectId: string, decisionType: string): NapiDecisionRecord[]
  searchDecisions(projectId: string, query: string): NapiDecisionRecord[]
  deleteDecision(projectId: string, id: string): boolean
  createAdr(projectId: string, input: CreateAdrInput): NapiAdr
  getAdr(projectId: string, id: string): NapiAdr | null
  getAllAdrs(projectId: string): NapiAdr[]
  formatAdrMarkdown(projectId: string, id: string): string | null
  getEditStats(projectId: string): NapiEditStats
  cleanup(projectId: string, beforeTimestamp: number): number
  invalidate(projectId: string): void
}

export declare function openHistoryStore(path: string): HistoryStoreHandle
export declare function createMemoryHistoryStore(): HistoryStoreHandle

export interface NapiFileEdit {
  path: string
  type: string
  additions: number
  deletions: number
  preHash?: string
  postHash?: string
}

export interface NapiEditRecord {
  id: string
  sessionId?: string
  timestamp: number
  description?: string
  edits: NapiFileEdit[]
  agent?: string
  model?: string
  tokensUsed?: number
  duration?: number
}

export interface CreateEditRecordInput {
  edits: NapiFileEdit[]
  sessionId?: string
  description?: string
  agent?: string
  model?: string
  tokensUsed?: number
  duration?: number
}

export interface NapiEditSession {
  id: string
  projectId: string
  startTime: number
  endTime?: number
  edits: string[]
  totalTokens: number
  totalDuration: number
  description?: string
}

export interface NapiDecisionRecord {
  id: string
  type: string
  title: string
  description: string
  rationale?: string
  alternatives?: string[]
  outcome?: string
  sessionId?: string
  files?: string[]
  tags?: string[]
  timestamp: number
}

export interface CreateDecisionInput {
  type: string
  title: string
  description: string
  rationale?: string
  alternatives?: string[]
  outcome?: string
  sessionId?: string
  files?: string[]
  tags?: string[]
}

export interface NapiAlternative {
  description: string
  rejected: boolean
  reason?: string
}

export interface NapiAdr {
  id: string
  title: string
  status: string
  context: string
  decision: string
  consequences: string[]
  alternatives?: NapiAlternative[]
  supersededBy?: string
  created: number
  updated: number
  tags?: string[]
}

export interface CreateAdrInput {
  title: string
  context: string
  decision: string
  consequences: string[]
  status?: string
  alternatives?: NapiAlternative[]
  tags?: string[]
}

export interface NapiAgentStats {
  name: string
  editCount: number
  tokenCount: number
}

export interface NapiFileEditCount {
  path: string
  count: number
}

export interface NapiEditStats {
  totalEdits: number
  totalAdditions: number
  totalDeletions: number
  totalFiles: number
  topFiles: NapiFileEditCount[]
  agentStats: NapiAgentStats[]
}

// ============================================================================
// Session Module Types
// ============================================================================

export declare class SessionStoreHandle {
  save(session: NapiSessionData): void
  load(id: string): NapiSessionData | null
  list(): NapiSessionData[]
  delete(id: string): boolean
}

export declare function openSessionStore(path: string): SessionStoreHandle

export interface NapiMessage {
  id: string
  role: string
  content: string
  timestamp: string
  tokens?: number
  toolCallId?: string
  toolName?: string
  compacted: boolean
}

export interface NapiSessionData {
  id: string
  name?: string
  cwd: string
  createdAt: string
  updatedAt: string
  messages: NapiMessage[]
}

// ============================================================================
// Compaction Module Types
// ============================================================================

/** Compaction strategy enum */
export declare const enum NapiCompactionStrategy {
  /** Remove oldest messages first */
  RemoveOldest = 'RemoveOldest',
  /** Summarize older messages (requires LLM - falls back to RemoveOldest in Rust) */
  Summarize = 'Summarize',
  /** Hybrid: summarize then remove */
  Hybrid = 'Hybrid'
}

/** Result of compaction operation */
export interface NapiCompactionResult {
  /** Number of messages before compaction */
  messagesBefore: number
  /** Number of messages after compaction */
  messagesAfter: number
  /** Tokens before compaction */
  tokensBefore: number
  /** Tokens after compaction */
  tokensAfter: number
  /** Summary generated (if any) */
  summary?: string
}

/** Combined result containing both metrics and compacted messages */
export interface NapiCompactResult {
  /** Compaction metrics (before/after counts) */
  result: NapiCompactionResult
  /** The compacted messages */
  messages: NapiMessage[]
}

/** Handle to a Compactor for managing context window */
export declare class CompactorHandle {
  /** Check if compaction is needed for the given messages */
  needsCompaction(messages: NapiMessage[]): boolean
  /** Compact messages to fit within token limit */
  compact(messages: NapiMessage[]): NapiCompactResult
  /** Set the compaction strategy */
  setStrategy(strategy: NapiCompactionStrategy): void
}

/** Create a new compactor with default settings (128k max, 100k target) */
export declare function createCompactor(): CompactorHandle

/** Create a compactor with custom token limits */
export declare function createCompactorWithLimits(maxTokens: number, targetTokens: number): CompactorHandle

/** Estimate token count for text (fast, approximate) */
export declare function estimateTokens(text: string): number

// ============================================================================
// Audit Module Types
// ============================================================================

export declare class NapiAuditLog {
  constructor()
  log(entry: NapiAuditEntryInput): Promise<string>
  query(filter: NapiAuditFilter): Promise<NapiAuditEntry[]>
  exportReport(sessionId: string): Promise<NapiAuditReport>
  count(filter?: NapiAuditFilter): Promise<number>
  clear(): Promise<void>
}

export interface NapiAuditEntryInput {
  sessionId: string
  entryType: NapiAuditEntryType
  action: string
  input: string
  result: NapiAuditResult
  risk?: NapiRiskLevel
  autoApproved?: boolean
  reason: string
  metadata: string
}

export interface NapiAuditEntry {
  id: string
  timestamp: number
  sessionId: string
  entryType: NapiAuditEntryType
  action: string
  input: string
  result: NapiAuditResult
  risk?: NapiRiskLevel
  autoApproved?: boolean
  reason: string
  metadata: string
}

export interface NapiAuditFilter {
  sessionId?: string
  entryType?: NapiAuditEntryType
  result?: NapiAuditResult
  risk?: NapiRiskLevel
  autoApproved?: boolean
  fromTimestamp?: number
  toTimestamp?: number
  action?: string
  limit?: number
  offset?: number
}

export interface NapiAuditReport {
  sessionId: string
  generatedAt: string
  summary: NapiAuditSummary
  entries: NapiAuditEntry[]
}

export interface NapiAuditSummary {
  totalEntries: number
  byType: any
  byResult: any
  byRisk: any
  autoApprovedCount: number
  timeRange: any
}

export declare const enum NapiAuditEntryType {
  Permission = 'Permission',
  ToolCall = 'ToolCall',
  Decision = 'Decision',
  StateChange = 'StateChange',
  Checkpoint = 'Checkpoint',
  Rollback = 'Rollback',
  Error = 'Error',
  SessionStart = 'SessionStart',
  SessionEnd = 'SessionEnd'
}

export declare const enum NapiAuditResult {
  Approved = 'Approved',
  Rejected = 'Rejected',
  Error = 'Error',
  Success = 'Success',
  Failed = 'Failed'
}

export declare const enum NapiRiskLevel {
  Safe = 'Safe',
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical'
}

// ============================================================================
// Security Module Types
// ============================================================================

export declare class PermissionManagerHandle {
  addRule(rule: NapiPermissionRule): void
  grant(permission: NapiPermission): void
  check(permission: NapiPermission): boolean
  clear(): void
}

export declare function createPermissionManager(): PermissionManagerHandle

export interface NapiPermission {
  tool: string
  action: string
  resource?: string
}

export interface NapiPermissionRule {
  permission: NapiPermission
  allow: boolean
  reason?: string
}

export declare class VaultHandle {
  set(entry: NapiSecretEntry): void
  get(name: string): NapiSecretEntry | null
  getValue(name: string): string | null
  delete(name: string): boolean
  list(): string[]
  save(): void
}

export declare function openVault(path: string, password: string): VaultHandle
export declare function createMemoryVault(password: string): VaultHandle

export interface NapiSecretEntry {
  name: string
  value: string
  description?: string
}

export declare class InjectionScannerHandle {
  scan(input: string): InjectionScanResult
  quickCheck(input: string): boolean
  sanitize(input: string): string
}

export declare function createInjectionScanner(): InjectionScannerHandle
export declare function scanInjection(input: string): InjectionScanResult
export declare function quickCheckInjection(input: string): boolean
export declare function sanitizeInjectionInput(input: string): string

export interface InjectionScanResult {
  detected: boolean
  confidence: number
  patterns: InjectionPattern[]
  sanitized?: string
  durationMs: number
}

export interface InjectionPattern {
  injectionType: string
  matched: string
  position: number
  severity: string
  description: string
}

// ============================================================================
// Context Module Types
// ============================================================================

export declare function scoreRelevance(query: string, content: string): NapiRelevanceScore
export declare function scoreFiles(query: string, files: NapiFileMetadata[]): NapiScoredFile[]

export interface NapiRelevanceScore {
  score: number
  keywordScore: number
  structuralScore: number
  recencyScore: number
  matchedKeywords: string[]
}

export interface NapiFileMetadata {
  path: string
  content: string
  modified?: number
  extension?: string
}

export interface NapiScoredFile {
  path: string
  score: NapiRelevanceScore
}

// ============================================================================
// LSP Module Types
// ============================================================================

/** LSP location (file + range) */
export interface LspLocation {
  /** File URI */
  uri: string
  /** Start line (0-indexed) */
  startLine: number
  /** Start character (0-indexed) */
  startCharacter: number
  /** End line (0-indexed) */
  endLine: number
  /** End character (0-indexed) */
  endCharacter: number
}

/** LSP document symbol */
export interface LspSymbol {
  /** Symbol name */
  name: string
  /** Symbol kind (Function, Class, Method, etc.) */
  kind: string
  /** Start line */
  startLine: number
  /** Start character */
  startCharacter: number
  /** End line */
  endLine: number
  /** End character */
  endCharacter: number
}

/** LSP completion item */
export interface LspCompletionItem {
  /** Display label */
  label: string
  /** Completion kind (Function, Variable, etc.) */
  kind?: string
  /** Additional detail */
  detail?: string
  /** Documentation */
  documentation?: string
  /** Text to insert */
  insertText?: string
}

/** LSP text edit */
export interface LspTextEdit {
  /** Start line */
  startLine: number
  /** Start character */
  startCharacter: number
  /** End line */
  endLine: number
  /** End character */
  endCharacter: number
  /** New text to insert */
  newText: string
}

/** LSP server status */
export interface LspServerStatus {
  status: string
  error?: string
}

/** LSP range */
export interface LspRange {
  /** Start line */
  startLine: number
  /** Start character */
  startCharacter: number
  /** End line */
  endLine: number
  /** End character */
  endCharacter: number
}

/** LSP workspace symbol (includes container name and file URI) */
export interface LspWorkspaceSymbol {
  /** Symbol name */
  name: string
  /** Symbol kind (Function, Class, Method, etc.) */
  kind: string
  /** Container name (e.g., class name for a method) */
  containerName?: string
  /** File URI */
  uri: string
  /** Start line */
  startLine: number
  /** Start character */
  startCharacter: number
  /** End line */
  endLine: number
  /** End character */
  endCharacter: number
}

/** LSP call hierarchy item */
export interface LspCallHierarchyItem {
  /** Symbol name */
  name: string
  /** Symbol kind (Function, Method, etc.) */
  kind: string
  /** Detail (e.g., signature) */
  detail?: string
  /** File URI */
  uri: string
  /** Range start line */
  startLine: number
  /** Range start character */
  startCharacter: number
  /** Range end line */
  endLine: number
  /** Range end character */
  endCharacter: number
  /** Selection range start line */
  selectionStartLine: number
  /** Selection range start character */
  selectionStartCharacter: number
  /** Selection range end line */
  selectionEndLine: number
  /** Selection range end character */
  selectionEndCharacter: number
}

/** LSP call hierarchy incoming call */
export interface LspCallHierarchyIncomingCall {
  /** The item that makes the call */
  from: LspCallHierarchyItem
  /** Ranges where this call happens */
  fromRanges: LspRange[]
}

/** LSP call hierarchy outgoing call */
export interface LspCallHierarchyOutgoingCall {
  /** The item being called */
  to: LspCallHierarchyItem
  /** Ranges where this call happens */
  fromRanges: LspRange[]
}

export declare class LspServerManagerHandle {
  // Basic methods
  startForFile(filePath: string): Promise<string>
  start(serverId: string, root: string): Promise<string>
  request(key: string, method: string, params: any): Promise<any>
  stop(key: string): Promise<void>
  status(key: string): Promise<LspServerStatus>
  allStatuses(): Promise<Record<string, LspServerStatus>>
  stopAll(): Promise<void>
  // Convenience methods
  hover(key: string, uri: string, line: number, character: number): Promise<string | null>
  gotoDefinition(key: string, uri: string, line: number, character: number): Promise<LspLocation[]>
  gotoTypeDefinition(key: string, uri: string, line: number, character: number): Promise<LspLocation[]>
  findReferences(key: string, uri: string, line: number, character: number, includeDeclaration?: boolean): Promise<LspLocation[]>
  documentSymbols(key: string, uri: string): Promise<LspSymbol[]>
  workspaceSymbol(key: string, query: string): Promise<LspWorkspaceSymbol[]>
  prepareCallHierarchy(key: string, uri: string, line: number, character: number): Promise<LspCallHierarchyItem[]>
  incomingCalls(key: string, item: LspCallHierarchyItem): Promise<LspCallHierarchyIncomingCall[]>
  outgoingCalls(key: string, item: LspCallHierarchyItem): Promise<LspCallHierarchyOutgoingCall[]>
  completion(key: string, uri: string, line: number, character: number): Promise<LspCompletionItem[]>
  formatDocument(key: string, uri: string, tabSize?: number, insertSpaces?: boolean): Promise<LspTextEdit[]>
  didOpen(key: string, uri: string, languageId: string, version: number, text: string): Promise<void>
  didClose(key: string, uri: string): Promise<void>
  didChange(key: string, uri: string, version: number, text: string): Promise<void>
}

export declare function createLspServerManager(): LspServerManagerHandle
export declare function detectLanguageId(extension: string): string

// ============================================================================
// Storage Module Types
// ============================================================================

export declare class KvStoreHandle {
  set(key: string[], value: string): Promise<void>
  get(key: string[]): Promise<string | null>
  delete(key: string[]): Promise<boolean>
  exists(key: string[]): Promise<boolean>
  list(prefix: string[]): Promise<string[]>
  count(prefix: string[]): Promise<number>
  deletePrefix(prefix: string[]): Promise<number>
  stats(): Promise<NapiStoreStats>
  healthCheck(): Promise<boolean>
  compact(): Promise<void>
  path(): string
  /** Set multiple key-value pairs in a single transaction */
  batchSet(items: NapiBatchItem[]): Promise<void>
  /** Get multiple values by key paths in a single operation */
  batchGet(keys: string[][]): Promise<(string | null)[]>
  /** Delete multiple keys in a single transaction */
  batchDelete(keys: string[][]): Promise<number>
  /** Get all key-value pairs matching a prefix */
  getPrefix(prefix: string[]): Promise<NapiBatchItem[]>
}

/** Key-value pair for batch operations */
export interface NapiBatchItem {
  /** Key path as array of strings (e.g., ["session", "abc123"]) */
  key: string[]
  /** JSON-encoded value */
  value: string
}

export type KVStoreHandle = KvStoreHandle

export declare function openKvStore(path: string): Promise<KvStoreHandle>
export declare function createMemoryKvStore(): KvStoreHandle

export interface NapiStoreStats {
  totalEntries: number
  totalSizeBytes: number
  oldestEntryMs?: number
  newestEntryMs?: number
}

// ============================================================================
// Shell Parser Types
// ============================================================================

export declare class ShellParserHandle {
  parse(command: string): any
  assessRisk(commands: string[]): any
  extractDirectories(command: string): string[]
  extractPermissionPatterns(command: string): any[]
}

export declare function parseShellCommand(command: string): any
export declare function assessShellCommandsRisk(commands: string[]): any
export declare function extractShellDirectories(command: string): string[]
export declare function extractShellPermissionPatterns(command: string): any[]
export declare function isFileCommand(command: string): boolean
export declare function isDangerousCommand(command: string): boolean

// ============================================================================
// Risk Assessment Types
// ============================================================================

export interface RiskResult {
  risk: string
  reason: string
  autoApprovable: boolean
}

export declare function assessBashRisk(command: string): RiskResult
export declare function assessFileRisk(path: string): RiskResult
export declare function getToolBaseRisk(tool: string): string
export declare function checkRiskThreshold(risk: string, threshold: string): boolean
export declare function parseRiskLevel(level: string): string

// ============================================================================
// Auto-Approve Engine Types
// ============================================================================

export interface AutoApproveConfig {
  enabled: boolean
  allowedTools: string[]
  riskThreshold: string
  timeoutMs: number
  unattended: boolean
}

export interface ToolInput {
  inputType: string
  command?: string
  path?: string
  json?: string
}

export interface ApprovalDecision {
  approved: boolean
  risk: string
  reason: string
  timeoutApproved: boolean
  autoApprovable: boolean
}

export interface ExecutionContext {
  sessionId: string
  iteration: number
  errors: number
  successes: number
  projectPath?: string
  isProduction: boolean
}

export interface AdaptiveRiskResult {
  baseRisk: string
  adjustedRisk: string
  adjustment: number
  adjustmentReason: string
}

export interface AuditEntry {
  timestamp: string
  permissionId?: string
  tool: string
  pattern?: string[]
  risk: string
  decision: string
  reason: string
}

export declare class AutoApproveEngineHandle {
  config(): AutoApproveConfig
  setConfig(config: AutoApproveConfig): void
  evaluate(tool: string, input?: ToolInput): ApprovalDecision
  evaluateAdaptive(tool: string, input: ToolInput | undefined, ctx: ExecutionContext): ApprovalDecision
  canAutoApprove(tool: string): boolean
  assessRisk(tool: string, input?: ToolInput): RiskResult
  evaluateAdaptiveRisk(tool: string, input: ToolInput | undefined, ctx: ExecutionContext): AdaptiveRiskResult
  auditLog(): AuditEntry[]
  clearAuditLog(): void
}

export declare function createAutoApproveEngine(config: AutoApproveConfig): AutoApproveEngineHandle
export declare function createSafeOnlyEngine(unattended: boolean): AutoApproveEngineHandle
export declare function createPermissiveEngine(unattended: boolean): AutoApproveEngineHandle
export declare function evaluateAutoApprove(config: AutoApproveConfig, tool: string, input?: ToolInput): ApprovalDecision
export declare function evaluateAdaptiveAutoApprove(config: AutoApproveConfig, tool: string, input: ToolInput | undefined, ctx: ExecutionContext): ApprovalDecision
export declare function canSafeAutoApprove(tool: string): boolean

// ============================================================================
// Autonomous State Types
// ============================================================================

export declare const AutonomousState: any
export declare const StateCategory: any
export declare const TaskPriority: any
export declare const TaskStatus: any

export declare class StateMachineHandle {
  transition(event: any): any
  currentState(): any
  history(): any[]
}

export declare function createStateMachine(config: any): StateMachineHandle

export declare class TaskQueueHandle {
  enqueue(task: any): string
  dequeue(): any
  peek(): any
  remove(id: string): boolean
  list(): any[]
  clear(): void
}

export declare function createTaskQueue(): TaskQueueHandle

// ============================================================================
// Provider Transform Types
// ============================================================================

export declare function normalizeMessages(messages: any[]): any[]
export declare function applyCaching(messages: any[]): any[]
export declare function remapProviderOptions(options: any): any
export declare function getSdkKey(provider: string): string
export declare function getTemperature(provider: string): number
export declare function getTopP(provider: string): number
export declare function getTopK(provider: string): number
export declare function transformMessages(provider: string, messages: any[]): any[]

// ============================================================================
// Message Store Types
// ============================================================================

export declare class MessageStoreHandle {
  push(message: NapiMessage): void
  messages(): NapiMessage[]
  lastN(n: number): NapiMessage[]
  totalTokens(): number
  len(): number
  isEmpty(): boolean
  add(message: any): void
  get(id: string): any
  list(): any[]
  delete(id: string): boolean
  clear(): void
}

export declare function createMessageStore(): MessageStoreHandle
export declare const MessageRole: any

// ============================================================================
// Injection Scanner Extended Types
// ============================================================================

export declare function createInjectionScannerWithConfig(config: any): InjectionScannerHandle
export declare function scanInjectionWithConfig(input: string, config: any): InjectionScanResult
export declare const InjectionSeverity: any
export declare const InjectionType: any

// ============================================================================
// Context Extended Types
// ============================================================================

export declare function scoreRelevanceWithConfig(query: string, content: string, config: any): NapiRelevanceScore

// ============================================================================
// Graph Module Types (matches napi/graph.rs)
// ============================================================================

/** Node data for graphs */
export interface NapiNodeData {
  id: string
  node_type: string
  payload: string
  created_at: number
  updated_at: number
}

/** Path finding result */
export interface NapiPathResult {
  found: boolean
  path: string[]
  nodes_visited: number
}

/** Cycle detection result */
export interface NapiCycleResult {
  has_cycles: boolean
  cycles: string[][]
}

/** Generic graph engine */
export declare class GraphEngineHandle {
  constructor()
  addNode(id: string, nodeType: string, payload: string): string
  getNode(id: string): NapiNodeData | null
  containsNode(id: string): boolean
  addEdge(source: string, target: string, relationship: string): string | null
  getSuccessors(id: string): string[]
  getPredecessors(id: string): string[]
  nodeCount(): number
  edgeCount(): number
  bfs(start: string): string[]
  dfs(start: string): string[]
  findPath(from: string, to: string): NapiPathResult
  hasCycles(): boolean
  detectCycles(): NapiCycleResult
  topologicalSort(): string[]
  getReachable(start: string, maxDepth: number): string[]
  toJson(): string
  static fromJson(json: string): GraphEngineHandle
  clear(): void
}

// --- Causal Graph Types ---

export interface NapiDecisionNode {
  id: string
  session_id: string
  agent_id: string
  prompt: string
  reasoning: string
  confidence: number
  timestamp: string
  context?: string
}

export interface NapiActionNode {
  id: string
  decision_id: string
  action_type: string
  description: string
  input?: string
  output?: string
  timestamp: string
  duration?: number
}

export interface NapiOutcomeNode {
  id: string
  action_id: string
  status: string
  description: string
  metrics?: string
  feedback?: string
  timestamp: string
}

export interface NapiCausalChain {
  decision: NapiDecisionNode
  actions: NapiActionNode[]
  outcomes: NapiOutcomeNode[]
}

export interface NapiCausalQuery {
  agent_id?: string
  session_id?: string
  action_type?: string
  status?: string
  min_confidence?: number
  date_from?: string
  date_to?: string
  limit?: number
}

export interface NapiCausalStats {
  total_decisions: number
  total_actions: number
  total_outcomes: number
  total_edges: number
  success_rate: number
  avg_confidence: number
}

/** Causal graph for Decision → Action → Outcome tracking */
export declare class CausalGraphHandle {
  constructor(projectId: string)
  recordDecision(
    sessionId: string,
    agentId: string,
    prompt: string,
    reasoning: string,
    confidence: number,
    context?: string
  ): NapiDecisionNode
  recordAction(
    decisionId: string,
    actionType: string,
    description: string,
    input?: string,
    output?: string,
    duration?: number
  ): NapiActionNode
  recordOutcome(
    actionId: string,
    status: string,
    description: string,
    metrics?: string,
    feedback?: string
  ): NapiOutcomeNode
  getDecision(id: string): NapiDecisionNode | null
  getDecisions(): NapiDecisionNode[]
  getCausalChain(decisionId: string): NapiCausalChain | null
  query(query: NapiCausalQuery): NapiCausalChain[]
  getSuccessRate(agentId?: string): number
  getStats(): NapiCausalStats
  hasCycles(): boolean
  toJson(): string
  static fromJson(json: string): CausalGraphHandle
}

// --- Call Graph Types ---

export interface NapiCallNode {
  id: string
  name: string
  kind: string
  file: string
  line: number
  character: number
  detail?: string
}

export interface NapiRecursionInfo {
  node: NapiCallNode
  recursion_type: string
  cycle: string[]
}

/** Call graph for function call relationships */
export declare class CallGraphHandle {
  constructor(projectId: string)
  addFunction(
    name: string,
    file: string,
    line: number,
    character: number,
    kind: string,
    detail?: string
  ): NapiCallNode
  addCall(callerId: string, calleeId: string, line: number, character: number): string | null
  getNode(id: string): NapiCallNode | null
  getNodes(): NapiCallNode[]
  getCallers(calleeId: string): NapiCallNode[]
  getCallees(callerId: string): NapiCallNode[]
  detectRecursion(): NapiRecursionInfo[]
  getEntryPoints(): NapiCallNode[]
  getLeafFunctions(): NapiCallNode[]
  toJson(): string
  static fromJson(json: string): CallGraphHandle
}

// --- Semantic Graph Types ---

export interface NapiSemanticNode {
  id: string
  node_type: string
  name: string
  file: string
  metadata?: string
}

export interface NapiSemanticStats {
  total_nodes: number
  total_edges: number
  files: number
  functions: number
  classes: number
  interfaces: number
  has_cycles: boolean
}

/** Semantic graph for code entity relationships */
export declare class SemanticGraphHandle {
  constructor(projectId: string)
  addFunction(name: string, file: string, signature?: string, exported?: boolean): NapiSemanticNode
  addClass(name: string, file: string, extendsClass?: string, methods?: string[]): NapiSemanticNode
  addInterface(name: string, file: string, extendsInterface?: string): NapiSemanticNode
  addFile(path: string): NapiSemanticNode
  addImport(importer: string, imported: string): string | null
  addExtends(child: string, parent: string): string | null
  addImplements(implementor: string, interfaceId: string): string | null
  addContains(container: string, contained: string): string | null
  getNode(id: string): NapiSemanticNode | null
  getNodes(): NapiSemanticNode[]
  getNodesByType(nodeType: string): NapiSemanticNode[]
  getImports(entityId: string): NapiSemanticNode[]
  getImporters(entityId: string): NapiSemanticNode[]
  getInheritanceChain(classId: string): NapiSemanticNode[]
  hasCircularDependencies(): boolean
  stats(): NapiSemanticStats
  toJson(): string
  static fromJson(json: string): SemanticGraphHandle
}

// ============================================================================
// Fingerprint Module Types
// ============================================================================

export declare class FingerprintEngineHandle {
  generate(content: string): any
  compare(a: any, b: any): number
}

export declare function generateFingerprint(content: string): any
export declare function fingerprintSimilarity(a: any, b: any): number
export declare function describeFingerprint(fp: any): string
export declare function contentHash(content: string): string

// ============================================================================
// Web Fingerprint Types
// ============================================================================

export declare class WebFingerprintEngineHandle {
  detect(html: string): any[]
  getCategories(): string[]
  getFingerprints(category?: string): any[]
}

export declare function detectWebTechnologies(html: string): any[]
export declare function getWebCategories(): string[]
export declare function getWebFingerprints(): any[]
export declare function getWebFingerprintsByCategory(category: string): any[]

// ============================================================================
// Java Analysis Types
// ============================================================================

export declare class JarAnalyzerHandle {
  analyze(path: string): any
  getSummary(): any
}

export declare function analyzeJar(path: string): any
export declare function jarAnalysisSummary(analysis: any): string
export declare function detectJavaTechnologies(analysis: any): any[]
export declare function parseClassFileSync(path: string): any

// ============================================================================
// Credential & Keyring Types
// ============================================================================

export declare class CredentialManagerHandle {
  set(name: string, value: string): void
  get(name: string): string | null
  delete(name: string): boolean
  list(): string[]
}

export declare class KeyringManagerHandle {
  set(service: string, account: string, password: string): void
  get(service: string, account: string): string | null
  delete(service: string, account: string): boolean
}

export declare function createCredentialManager(): CredentialManagerHandle
export declare function createFileCredentialManager(path: string): CredentialManagerHandle
export declare function createKeyringManager(): KeyringManagerHandle
export declare function createFileKeyringManager(path: string): KeyringManagerHandle
export declare function isKeyringAvailable(): boolean
export declare const CredentialType: any
export declare const KeyringBackend: any

// ============================================================================
// MCP Types
// ============================================================================

export declare class McpAuthStoreHandle {
  set(server: string, token: string): void
  get(server: string): string | null
  delete(server: string): boolean
  list(): string[]
}

/** MCP resource definition */
export interface McpResource {
  uri: string
  name: string
  description?: string
  mime_type?: string
}

/** MCP prompt argument */
export interface McpPromptArgument {
  name: string
  description?: string
  required: boolean
}

/** MCP prompt definition */
export interface McpPrompt {
  name: string
  description?: string
  arguments: McpPromptArgument[]
}

/** MCP prompt result */
export interface McpPromptResult {
  description?: string
  messages: unknown[]
}

export declare class McpClientManagerHandle {
  /** Add a client */
  add(name: string, config: {
    name: string
    transport: string
    command?: string[]
    url?: string
    environment?: Record<string, string>
    timeout_ms?: number
    headers?: Record<string, string>
    cwd?: string
    oauth?: {
      client_id?: string
      client_secret?: string
      scope?: string
    }
    oauth_disabled?: boolean
  }): Promise<{
    status: string
    error?: string
  }>
  /** Get connection status for all clients */
  status(): Promise<Record<string, { status: string; error?: string }>>
  /** List all tools from all connected clients */
  listTools(): Promise<Record<string, { name: string; description: string; input_schema: unknown }>>
  /** Call a tool on a specific client */
  callTool(clientName: string, toolName: string, args: unknown): Promise<{ content: unknown[]; is_error: boolean }>
  /** Remove a client */
  remove(name: string): Promise<void>
  /** Close all connections */
  closeAll(): Promise<void>
  /** List resources from a specific client */
  listResources(clientName: string): Promise<McpResource[]>
  /** Read a resource from a specific client */
  readResource(clientName: string, uri: string): Promise<unknown>
  /** List prompts from a specific client */
  listPrompts(clientName: string): Promise<McpPrompt[]>
  /** Get a prompt from a specific client */
  getPrompt(clientName: string, promptName: string, args?: unknown): Promise<McpPromptResult>
  /** Load OAuth credentials from storage */
  loadOauth(): Promise<void>
  /** Start OAuth authentication flow */
  startOauth(serverName: string, serverUrl: string, redirectUri: string, config?: {
    client_id?: string
    client_secret?: string
    scope?: string
  }): Promise<string>
  /** Complete OAuth authentication */
  finishOauth(serverName: string, authorizationCode: string, state: string): Promise<void>
  /** Remove OAuth credentials */
  removeOauth(serverName: string): Promise<void>
  /** Get OAuth authentication status */
  getOauthStatus(serverName: string): Promise<string>
  /** Check if we have OAuth credentials */
  hasOauthCredentials(serverName: string): Promise<boolean>
  /** Cancel pending OAuth flow */
  cancelOauth(serverName: string): Promise<void>
}

export declare function createMcpAuthStore(): McpAuthStoreHandle
export declare function createFileMcpAuthStore(path: string): McpAuthStoreHandle
export declare function createMcpClientManager(): McpClientManagerHandle
export declare const McpTransportType: any

// ============================================================================
// Trace Types
// ============================================================================

export declare class TraceStoreHandle {
  record(trace: any): void
  query(filter: any): any[]
  clear(): void
}

export declare function openTraceStore(path: string): TraceStoreHandle
export declare function createMemoryTraceStore(): TraceStoreHandle

// ============================================================================
// Editor & Patch Types
// ============================================================================

export declare class EditorHandle {
  open(path: string): void
  edit(operation: any): void
  save(): void
  close(): void
}

export declare class PatchApplicatorHandle {
  apply(patch: any): any
  revert(patch: any): any
}

export declare function editFile(path: string, operation: any): any
export declare function computeDiff(a: string, b: string): any
export declare function replaceWithFuzzyMatch(content: string, search: string, replace: string): any
export declare function findBestMatch(content: string, pattern: string): any
export declare function readFile(path: string): string
export declare const NapiPatchType: any

// ============================================================================
// Utility Functions
// ============================================================================

export declare function glob(pattern: string, options?: any): string[]
export declare function grep(pattern: string, path: string, options?: any): any[]
export declare function bytesToVector(bytes: Uint8Array): number[]
export declare function vectorToBytes(vector: number[]): Uint8Array
export declare function normalizeVector(vector: number[]): number[]
export declare function cosineSimilarity(a: number[], b: number[]): number
export declare function vectorDistance(a: number[], b: number[]): number
export declare function hybridMergeResults(results: any[], config?: any): any[]
export declare function chunkText(text: string): string[]
export declare function chunkTextWithConfig(text: string, config: any): string[]
export declare function estimateTokens(text: string): number
export declare function levenshteinDistance(a: string, b: string): number
export declare function similarityRatio(a: string, b: string): number

// ============================================================================
// Project Detection Types
// ============================================================================

export declare const NapiFrameworkType: any
export declare const NapiPackageManager: any
export declare const NapiProjectLanguage: any

// ============================================================================
// Other Common Types
// ============================================================================

export declare function version(): string
export declare function init(): void

// ============================================================================
// Git Operations Types (Phase 8.1)
// ============================================================================

export interface NapiGitStatus {
  modified: string[]
  added: string[]
  deleted: string[]
  renamed: Record<string, string>
  untracked: string[]
  branch: string
  ahead: number
  behind: number
  files: NapiFileStatus[]
}

export interface NapiFileStatus {
  path: string
  status: string
  staged: boolean
  oldPath?: string
}

export interface NapiCommitResult {
  success: boolean
  commitHash?: string
  error?: string
}

export interface NapiCommitInfo {
  hash: string
  message: string
  author: string
  date: number
}

export interface NapiDiffFile {
  path: string
  status: string
  additions: number
  deletions: number
  patch?: string
}

export interface NapiDiffResult {
  files: NapiDiffFile[]
  insertions: number
  deletions: number
  filesChanged: number
}

export interface NapiOperationResult {
  success: boolean
  error?: string
}

export interface NapiInitOptions {
  defaultBranch?: string
  initialCommit?: boolean
  commitMessage?: string
}

export interface NapiCloneOptions {
  depth?: number
  branch?: string
  reinitialize?: boolean
}

export interface NapiWorktreeInfo {
  /** The name of the worktree (used to identify it in git) */
  name: string
  /** The filesystem path to the worktree */
  path: string
  /** The branch checked out in the worktree */
  branch: string
  /** Whether the worktree is locked */
  locked: boolean
  /** Whether the worktree is prunable (invalid/missing) */
  prunable: boolean
}

export declare class GitOpsHandle {
  path(): string
  status(): NapiGitStatus
  currentBranch(): string
  isClean(): boolean
  commit(message: string, addAll?: boolean, allowEmpty?: boolean): NapiCommitResult
  commits(limit?: number): NapiCommitInfo[]
  currentCommit(): string | null
  reset(commitHash: string, hard?: boolean): NapiOperationResult
  diff(from?: string, to?: string): NapiDiffResult
  changedFiles(sinceCommit?: string): string[]
  stash(message?: string): NapiOperationResult
  stashPop(): NapiOperationResult
  stashList(): string[]
  addRemote(name: string, url: string): NapiOperationResult
  removeRemote(name: string): NapiOperationResult
  remoteUrl(name: string): string | null
  remotes(): string[]
  fetch(remote?: string): NapiOperationResult
  push(remote?: string, branch?: string, setUpstream?: boolean): NapiOperationResult
  createBranch(name: string, from?: string): NapiOperationResult
  checkout(refName: string): NapiOperationResult
  deleteBranch(name: string, force?: boolean): NapiOperationResult
  branches(includeRemote?: boolean): string[]
  stageFiles(paths: string[]): NapiOperationResult
  unstageFiles(paths: string[]): NapiOperationResult
  // Worktree operations
  listWorktrees(): NapiWorktreeInfo[]
  addWorktree(name: string, path: string, branch?: string): NapiWorktreeInfo
  removeWorktree(name: string, force?: boolean): NapiOperationResult
  pruneWorktrees(): NapiOperationResult
  lockWorktree(name: string, reason?: string): NapiOperationResult
  unlockWorktree(name: string): NapiOperationResult
  getWorktree(name: string): NapiWorktreeInfo | null
  refExists(refName: string): boolean
}

export declare function openGitRepo(path: string): GitOpsHandle
export declare function initGitRepo(path: string, options?: NapiInitOptions): GitOpsHandle
export declare function cloneGitRepo(url: string, path: string, options?: NapiCloneOptions): GitOpsHandle
export declare function isGitRepo(path: string): boolean

// ============================================================================
// Markdown Module Types (Phase 11)
// ============================================================================

export interface NapiMarkdownHeading {
  /** Heading level (1-6) */
  level: number
  /** Heading text content */
  text: string
  /** Line number in source (1-indexed) */
  line: number
}

export interface NapiMarkdownCodeBlock {
  /** Language identifier (e.g., "rust", "python") */
  language: string | null
  /** Code content */
  code: string
  /** Start line in source (1-indexed) */
  startLine: number
  /** End line in source (1-indexed) */
  endLine: number
}

export interface NapiMarkdownLink {
  /** URL destination */
  url: string
  /** Link text */
  text: string
  /** Optional title attribute */
  title: string | null
  /** Line number in source (1-indexed) */
  line: number
}

export interface NapiMarkdownImage {
  /** Image URL/path */
  url: string
  /** Alt text */
  alt: string
  /** Optional title attribute */
  title: string | null
  /** Line number in source (1-indexed) */
  line: number
}

export interface NapiMarkdownNode {
  /**
   * Node type: "heading", "paragraph", "code_block", "inline_code", "list",
   * "block_quote", "link", "image", "horizontal_rule", "table", "html",
   * "task_list_item", "footnote_definition"
   */
  nodeType: string
  /** JSON-serialized content (structure depends on nodeType) */
  content: string
}

/** Parse markdown text into a vector of typed nodes */
export declare function parseMarkdown(text: string): NapiMarkdownNode[]

/** Extract all headings from markdown text */
export declare function extractMarkdownHeadings(text: string): NapiMarkdownHeading[]

/** Extract all fenced and indented code blocks from markdown text */
export declare function extractMarkdownCodeBlocks(text: string): NapiMarkdownCodeBlock[]

/** Extract all links from markdown text */
export declare function extractMarkdownLinks(text: string): NapiMarkdownLink[]

/** Extract all images from markdown text */
export declare function extractMarkdownImages(text: string): NapiMarkdownImage[]

/** Render markdown text to HTML */
export declare function renderMarkdownToHtml(text: string): string

/** Extract frontmatter from markdown text (YAML between --- delimiters) */
export declare function extractMarkdownFrontmatter(text: string): string | null

/** Remove frontmatter from markdown text */
export declare function stripMarkdownFrontmatter(text: string): string

// ============================================================================
// PTY Module Types (Phase 12)
// ============================================================================

export interface NapiPtyConfig {
  /** Initial terminal width in columns */
  cols?: number
  /** Initial terminal height in rows */
  rows?: number
  /** Shell to use */
  shell?: string
  /** Working directory */
  cwd?: string
  /** Environment variables */
  env?: Record<string, string>
  /** Inherit environment from parent */
  inheritEnv?: boolean
}

export declare const enum NapiPtyState {
  Running = 'Running',
  Exited = 'Exited',
  Killed = 'Killed',
  Error = 'Error'
}

export interface NapiPtyInfo {
  /** Session ID */
  id: string
  /** Current state */
  state: NapiPtyState
  /** Exit code (if exited) */
  exitCode: number | null
  /** Terminal width */
  cols: number
  /** Terminal height */
  rows: number
  /** Shell being used */
  shell: string
  /** Working directory */
  cwd: string
}

export declare class PtySessionHandle {
  /** Get the session ID */
  readonly id: string
  /** Check if the session is running */
  isRunning(): boolean
  /** Get session info */
  info(): NapiPtyInfo
  /** Read output from the PTY (non-blocking) */
  read(): Buffer
  /** Read output with timeout (milliseconds) */
  readWithTimeout(timeoutMs: number): Buffer
  /** Write data to the PTY */
  write(data: Buffer): void
  /** Write a line (with newline) to the PTY */
  writeLine(line: string): void
  /** Resize the terminal */
  resize(cols: number, rows: number): void
  /** Kill the process */
  kill(): void
  /** Wait for the process to exit */
  wait(): number
  /** Wait for the process with timeout (milliseconds) */
  waitWithTimeout(timeoutMs: number): number | null
  /** Get exit code (if exited) */
  exitCode(): number | null
}

export declare class PtyManagerHandle {
  constructor()
  /** Create a new shell session */
  create(config: NapiPtyConfig): string
  /** Create a new session with a specific command */
  createCommand(command: string, args: string[], config: NapiPtyConfig): string
  /** List all session IDs */
  list(): string[]
  /** List all session info */
  listInfo(): NapiPtyInfo[]
  /** Clean up exited sessions */
  cleanup(): void
  /** Kill all sessions */
  killAll(): void
}

/** Spawn a new PTY session */
export declare function spawnPty(config: NapiPtyConfig): PtySessionHandle

/** Spawn a new PTY session with a specific command */
export declare function spawnPtyCommand(command: string, args: string[], config: NapiPtyConfig): PtySessionHandle

// ============================================================================
// Config Loader Types
// ============================================================================

/** Provider configuration from NAPI */
export interface NapiProviderConfig {
  apiKey?: string
  baseUrl?: string
  organization?: string
  whitelist: string[]
  blacklist: string[]
}

/** Agent configuration from NAPI */
export interface NapiAgentConfig {
  model?: string
  temperature?: number
  topP?: number
  prompt?: string
  description?: string
  disable?: boolean
  mode?: string
  hidden?: boolean
  color?: string
  steps?: number
}

/** Command configuration from NAPI */
export interface NapiCommandConfig {
  template: string
  description?: string
  agent?: string
  model?: string
  subtask?: boolean
}

/** Secrets configuration from NAPI */
export interface NapiSecretsConfig {
  llm: Record<string, string | null>
  channels: Record<string, string | null>
  external: Record<string, string | null>
}

/** Main configuration object from NAPI */
export interface NapiConfig {
  theme?: string
  logLevel?: string
  model?: string
  smallModel?: string
  defaultAgent?: string
  username?: string
  disabledProviders: string[]
  enabledProviders: string[]
  instructions: string[]
}

/** Validation issue from schema validation */
export interface NapiValidationIssue {
  path: string
  message: string
}

/** Handle to a configuration loader for high-performance operations */
export declare class ConfigLoaderHandle {
  /** Get the config directory path */
  configDir(): string
  /** Get the home directory path */
  homeDir(): string
  /** Add a search path */
  addPath(path: string): void
  /** Load configuration from a single file (returns JSON string) */
  loadFile(path: string): string
  /** Parse JSONC content (returns JSON string) */
  parseJsonc(content: string): string
  /** Load merged configuration from all paths (returns JSON string) */
  loadMerged(): string
  /** Get simplified config object (call loadMerged first) */
  getConfig(): NapiConfig
  /** Get provider configurations (call loadMerged first) */
  getProviders(): Record<string, NapiProviderConfig>
  /** Get agent configurations (call loadMerged first) */
  getAgents(): Record<string, NapiAgentConfig>
  /** Get command configurations (call loadMerged first) */
  getCommands(): Record<string, NapiCommandConfig>
  /** Get secrets configuration (call loadMerged first) */
  getSecrets(): NapiSecretsConfig | null
  /** Scan directory for .codecoder directories */
  scanDirectory(start: string, stop?: string): string[]
  /** Find config files in a directory */
  findConfigFiles(dir: string): string[]
  /** Save configuration to file */
  save(configJson: string): void
  /** Load secrets from secrets.json */
  loadSecrets(): Record<string, string>
  /** Merge two configs (base + source), returns JSON string */
  mergeConfigs(baseJson: string, sourceJson: string): string
  /** Validate configuration against schema */
  validateSchema(configJson: string, schemaJson: string): NapiValidationIssue[]
  /** Check if configuration is valid against schema */
  isValidSchema(configJson: string, schemaJson: string): boolean
}

/** Create a new config loader */
export declare function createConfigLoader(paths?: string[]): ConfigLoaderHandle

// ============================================================================
// Compaction Types
// ============================================================================

/** Compaction strategy */
export type NapiCompactionStrategy = 'none' | 'prune' | 'summary' | 'hybrid'

/** Compaction result */
export interface NapiCompactionResult {
  compacted: boolean
  strategy: NapiCompactionStrategy
  originalTokens: number
  newTokens: number
  savedTokens: number
  summary?: string
}

/** Handle to a compactor for context window management */
export declare class CompactorHandle {
  /** Check if compaction is needed */
  needsCompaction(currentTokens: number): boolean
  /** Perform compaction on messages (returns JSON string) */
  compact(messagesJson: string): string
  /** Get current strategy */
  getStrategy(): NapiCompactionStrategy
  /** Set compaction strategy */
  setStrategy(strategy: NapiCompactionStrategy): void
}

/** Create a new compactor with default settings */
export declare function createCompactor(): CompactorHandle

/** Create a new compactor with custom limits */
export declare function createCompactorWithLimits(contextLimit: number, targetRatio: number): CompactorHandle

// ============================================================================
// File Watcher Module Types
// ============================================================================

/** Watch event kind enum */
export declare const enum WatchEventKind {
  /** File created */
  Add = 'Add',
  /** File modified */
  Change = 'Change',
  /** File deleted */
  Unlink = 'Unlink',
  /** File renamed */
  Rename = 'Rename'
}

/** File watch event */
export interface WatchEvent {
  /** Affected file path */
  path: string
  /** Event type: 'add' | 'change' | 'unlink' | 'rename' */
  kind: string
  /** Timestamp (Unix ms) */
  timestamp: number
}

/** File watcher configuration */
export interface FileWatcherConfig {
  /** Debounce duration in milliseconds (default: 100) */
  debounceMs?: number
  /** Whether to watch recursively (default: true) */
  recursive?: boolean
  /** Patterns to ignore (gitignore style) */
  ignore?: string[]
}

/** Handle to a file watcher */
export declare class FileWatcherHandle {
  /** Subscribe to file changes in a directory */
  subscribe(path: string, callback: (path: string, event: string) => void): void
  /** Unsubscribe from all watchers */
  unsubscribeAll(): void
  /** Get the number of active subscriptions */
  subscriptionCount(): number
  /** Check if currently watching any paths */
  isWatching(): boolean
}

/** Create a new file watcher with default configuration */
export declare function createFileWatcher(): FileWatcherHandle

/** Create a new file watcher with custom configuration */
export declare function createFileWatcherWithConfig(config: FileWatcherConfig): FileWatcherHandle

/** Watch a single path with a callback (convenience function) */
export declare function watchPath(
  path: string,
  callback: (path: string, event: string) => void,
  config?: FileWatcherConfig
): FileWatcherHandle

// ============================================================================
// Hook Pattern Matching Module Types
// ============================================================================

/** Result of pattern matching */
export interface PatternMatchResult {
  /** Whether any pattern matched */
  found: boolean
  /** All matched strings */
  matches: string[]
  /** Map of pattern to its matches */
  matchesByPattern: Record<string, string[]>
}

/** Line match information for content scanning */
export interface ContentMatchResult {
  /** Whether any pattern matched */
  found: boolean
  /** All matched strings */
  matches: string[]
  /** Lines where matches were found (1-indexed) */
  lines: number[]
  /** Map of pattern to line numbers where it matched */
  linesByPattern: Record<string, number[]>
}

/** Handle to a compiled pattern set for reuse */
export declare class PatternSetHandle {
  /** Scan content for any matching patterns */
  scan(content: string): PatternMatchResult
  /** Scan content and report line numbers for matches */
  scanContent(content: string): ContentMatchResult
  /** Check if a tool name matches a pattern */
  matchesTool(tool: string): boolean
  /** Get the number of patterns in this set */
  patternCount(): number
}

/** Create a compiled pattern set for efficient reuse */
export declare function createPatternSet(patterns: string[]): PatternSetHandle

/** Scan content for patterns (one-shot, no precompilation) */
export declare function scanPatterns(content: string, patterns: string[]): PatternMatchResult

/** Scan content for patterns and report line numbers (one-shot) */
export declare function scanContentPatterns(content: string, patterns: string[]): ContentMatchResult

/** Check if a string matches a regex pattern (anchored: ^pattern$) */
export declare function matchesPattern(pattern: string, value: string): boolean

/** Check if a string matches a regex pattern (unanchored) */
export declare function containsPattern(pattern: string, value: string): boolean

// ============================================================================
// Tool Registry Module Types
// ============================================================================

/** Tool specification for LLM function calling */
export interface NapiToolSpec {
  /** Tool name (unique identifier) */
  name: string
  /** Human-readable description for the LLM */
  description: string
  /** JSON Schema for the tool's parameters (as JSON string) */
  parametersSchema: string
  /** Whether this tool is implemented natively in Rust */
  native: boolean
}

/** Result of tool execution */
export interface NapiToolExecuteResult {
  /** Whether the tool succeeded */
  success: boolean
  /** Tool output (stdout, result text, etc.) */
  output: string
  /** Error message if failed */
  error?: string
  /** Execution duration in milliseconds */
  durationMs: number
}

/** Result of argument validation */
export interface NapiValidationResult {
  /** Whether the arguments are valid */
  valid: boolean
  /** Validation error messages */
  errors: string[]
}

/** Handle to the tool registry for unified tool discovery and execution */
export declare class ToolRegistryHandle {
  constructor()
  /** List all available tool specifications */
  listTools(): NapiToolSpec[]
  /** Get a specific tool's specification by name */
  getSpec(name: string): NapiToolSpec | null
  /** Check if a tool exists in the registry */
  hasTool(name: string): boolean
  /** Get the number of registered tools */
  toolCount(): number
  /** Validate tool arguments against its schema */
  validateArgs(name: string, argsJson: string): NapiValidationResult
  /** Execute a tool with the given arguments (async) */
  execute(name: string, argsJson: string): Promise<NapiToolExecuteResult>
}

/** Create a new tool registry with all built-in tools */
export declare function createToolRegistry(): ToolRegistryHandle

/** Get specifications for all built-in Rust tools (without creating a registry) */
export declare function getBuiltinToolSpecs(): NapiToolSpec[]

/** Get the list of tool names that have native Rust implementations */
export declare function getNativeToolNames(): string[]

