// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  const report = typeof process.report.getReport === 'function' ? process.report.getReport() : null
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('../codecoder-core.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm') {
      try {
        return require('../codecoder-core.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-android-arm-eabi')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('../codecoder-core.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-win32-x64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'ia32') {
      try {
        return require('../codecoder-core.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-win32-ia32-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('../codecoder-core.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-win32-arm64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
        return require('../codecoder-core.darwin-universal.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-darwin-universal')
      } catch (e) {
        loadErrors.push(e)
      }

    if (process.arch === 'x64') {
      try {
        return require('../codecoder-core.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-darwin-x64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('../codecoder-core.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-darwin-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('../codecoder-core.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-freebsd-x64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('../codecoder-core.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-freebsd-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
        return require('../codecoder-core.linux-x64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-x64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('../codecoder-core.linux-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-x64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
        return require('../codecoder-core.linux-arm64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-arm64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('../codecoder-core.linux-arm64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-arm64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
        return require('../codecoder-core.linux-arm-musleabihf.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-arm-musleabihf')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('../codecoder-core.linux-arm-gnueabihf.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-arm-gnueabihf')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
        return require('../codecoder-core.linux-riscv64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-riscv64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('../codecoder-core.linux-riscv64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-riscv64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('../codecoder-core.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-ppc64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 's390x') {
      try {
        return require('../codecoder-core.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@codecoder-ai/core-linux-s390x-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('../codecoder-core.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('@codecoder-ai/core-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    // TODO Link to documentation with potential fixes
    //  - The package owner could build/publish bindings for this arch
    //  - The user may need to bundle the correct files
    //  - The user may need to re-install node_modules to get new packages
    throw new Error('Failed to load native binding', { cause: loadErrors })
  }
  throw new Error(`Failed to load native binding`)
}

module.exports.CallGraphHandle = nativeBinding.CallGraphHandle
module.exports.CausalGraphHandle = nativeBinding.CausalGraphHandle
module.exports.CredentialManagerHandle = nativeBinding.CredentialManagerHandle
module.exports.EditorHandle = nativeBinding.EditorHandle
module.exports.FingerprintEngineHandle = nativeBinding.FingerprintEngineHandle
module.exports.GraphEngineHandle = nativeBinding.GraphEngineHandle
module.exports.InjectionScannerHandle = nativeBinding.InjectionScannerHandle
module.exports.JarAnalyzerHandle = nativeBinding.JarAnalyzerHandle
module.exports.KeyringManagerHandle = nativeBinding.KeyringManagerHandle
module.exports.KvStoreHandle = nativeBinding.KvStoreHandle
module.exports.KVStoreHandle = nativeBinding.KVStoreHandle
module.exports.LspServerManagerHandle = nativeBinding.LspServerManagerHandle
module.exports.McpAuthStoreHandle = nativeBinding.McpAuthStoreHandle
module.exports.McpClientManagerHandle = nativeBinding.McpClientManagerHandle
module.exports.MessageStoreHandle = nativeBinding.MessageStoreHandle
module.exports.NapiAuditLog = nativeBinding.NapiAuditLog
module.exports.PatchApplicatorHandle = nativeBinding.PatchApplicatorHandle
module.exports.PermissionManagerHandle = nativeBinding.PermissionManagerHandle
module.exports.SemanticGraphHandle = nativeBinding.SemanticGraphHandle
module.exports.SessionStoreHandle = nativeBinding.SessionStoreHandle
module.exports.StateMachineHandle = nativeBinding.StateMachineHandle
module.exports.TaskQueueHandle = nativeBinding.TaskQueueHandle
module.exports.TraceStoreHandle = nativeBinding.TraceStoreHandle
module.exports.VaultHandle = nativeBinding.VaultHandle
module.exports.WebFingerprintEngineHandle = nativeBinding.WebFingerprintEngineHandle
module.exports.analyzeJar = nativeBinding.analyzeJar
module.exports.applyCaching = nativeBinding.applyCaching
module.exports.AutonomousState = nativeBinding.AutonomousState
module.exports.bytesToVector = nativeBinding.bytesToVector
module.exports.chunkText = nativeBinding.chunkText
module.exports.chunkTextWithConfig = nativeBinding.chunkTextWithConfig
module.exports.computeDiff = nativeBinding.computeDiff
module.exports.contentHash = nativeBinding.contentHash
module.exports.cosineSimilarity = nativeBinding.cosineSimilarity
module.exports.createCredentialManager = nativeBinding.createCredentialManager
module.exports.createFileCredentialManager = nativeBinding.createFileCredentialManager
module.exports.createFileKeyringManager = nativeBinding.createFileKeyringManager
module.exports.createFileMcpAuthStore = nativeBinding.createFileMcpAuthStore
module.exports.createInjectionScanner = nativeBinding.createInjectionScanner
module.exports.createInjectionScannerWithConfig = nativeBinding.createInjectionScannerWithConfig
module.exports.createKeyringManager = nativeBinding.createKeyringManager
module.exports.createLspServerManager = nativeBinding.createLspServerManager
module.exports.createMcpAuthStore = nativeBinding.createMcpAuthStore
module.exports.createMcpClientManager = nativeBinding.createMcpClientManager
module.exports.createMemoryKvStore = nativeBinding.createMemoryKvStore
module.exports.createMemoryTraceStore = nativeBinding.createMemoryTraceStore
module.exports.createMemoryVault = nativeBinding.createMemoryVault
module.exports.createMessageStore = nativeBinding.createMessageStore
module.exports.createPermissionManager = nativeBinding.createPermissionManager
module.exports.createStateMachine = nativeBinding.createStateMachine
module.exports.createTaskQueue = nativeBinding.createTaskQueue
module.exports.CredentialType = nativeBinding.CredentialType
module.exports.describeFingerprint = nativeBinding.describeFingerprint
module.exports.detectJavaTechnologies = nativeBinding.detectJavaTechnologies
module.exports.detectWebTechnologies = nativeBinding.detectWebTechnologies
module.exports.editFile = nativeBinding.editFile
module.exports.estimateTokens = nativeBinding.estimateTokens
module.exports.findBestMatch = nativeBinding.findBestMatch
module.exports.fingerprintSimilarity = nativeBinding.fingerprintSimilarity
module.exports.generateFingerprint = nativeBinding.generateFingerprint
module.exports.getSdkKey = nativeBinding.getSdkKey
module.exports.getTemperature = nativeBinding.getTemperature
module.exports.getTopK = nativeBinding.getTopK
module.exports.getTopP = nativeBinding.getTopP
module.exports.getWebCategories = nativeBinding.getWebCategories
module.exports.getWebFingerprints = nativeBinding.getWebFingerprints
module.exports.getWebFingerprintsByCategory = nativeBinding.getWebFingerprintsByCategory
module.exports.glob = nativeBinding.glob
module.exports.grep = nativeBinding.grep
module.exports.hybridMergeResults = nativeBinding.hybridMergeResults
module.exports.init = nativeBinding.init
module.exports.InjectionSeverity = nativeBinding.InjectionSeverity
module.exports.InjectionType = nativeBinding.InjectionType
module.exports.isKeyringAvailable = nativeBinding.isKeyringAvailable
module.exports.jarAnalysisSummary = nativeBinding.jarAnalysisSummary
module.exports.KeyringBackend = nativeBinding.KeyringBackend
module.exports.levenshteinDistance = nativeBinding.levenshteinDistance
module.exports.McpTransportType = nativeBinding.McpTransportType
module.exports.MessageRole = nativeBinding.MessageRole
module.exports.NapiAuditEntryType = nativeBinding.NapiAuditEntryType
module.exports.NapiAuditResult = nativeBinding.NapiAuditResult
module.exports.NapiFrameworkType = nativeBinding.NapiFrameworkType
module.exports.NapiPackageManager = nativeBinding.NapiPackageManager
module.exports.NapiPatchType = nativeBinding.NapiPatchType
module.exports.NapiProjectLanguage = nativeBinding.NapiProjectLanguage
module.exports.NapiRiskLevel = nativeBinding.NapiRiskLevel
module.exports.normalizeMessages = nativeBinding.normalizeMessages
module.exports.normalizeVector = nativeBinding.normalizeVector
module.exports.openKvStore = nativeBinding.openKvStore
module.exports.openSessionStore = nativeBinding.openSessionStore
module.exports.openTraceStore = nativeBinding.openTraceStore
module.exports.openVault = nativeBinding.openVault
module.exports.parseClassFileSync = nativeBinding.parseClassFileSync
module.exports.quickCheckInjection = nativeBinding.quickCheckInjection
module.exports.readFile = nativeBinding.readFile
module.exports.remapProviderOptions = nativeBinding.remapProviderOptions
module.exports.replaceWithFuzzyMatch = nativeBinding.replaceWithFuzzyMatch
module.exports.sanitizeInjectionInput = nativeBinding.sanitizeInjectionInput
module.exports.scanInjection = nativeBinding.scanInjection
module.exports.scanInjectionWithConfig = nativeBinding.scanInjectionWithConfig
module.exports.scoreFiles = nativeBinding.scoreFiles
module.exports.scoreRelevance = nativeBinding.scoreRelevance
module.exports.scoreRelevanceWithConfig = nativeBinding.scoreRelevanceWithConfig
module.exports.similarityRatio = nativeBinding.similarityRatio
module.exports.StateCategory = nativeBinding.StateCategory
module.exports.TaskPriority = nativeBinding.TaskPriority
module.exports.TaskStatus = nativeBinding.TaskStatus
module.exports.transformMessages = nativeBinding.transformMessages
module.exports.vectorDistance = nativeBinding.vectorDistance
module.exports.vectorToBytes = nativeBinding.vectorToBytes
module.exports.version = nativeBinding.version

// History module exports
module.exports.HistoryStoreHandle = nativeBinding.HistoryStoreHandle
module.exports.openHistoryStore = nativeBinding.openHistoryStore
module.exports.createMemoryHistoryStore = nativeBinding.createMemoryHistoryStore
module.exports.ShellParserHandle = nativeBinding.ShellParserHandle
module.exports.parseShellCommand = nativeBinding.parseShellCommand
module.exports.assessShellCommandsRisk = nativeBinding.assessShellCommandsRisk
module.exports.extractShellDirectories = nativeBinding.extractShellDirectories
module.exports.extractShellPermissionPatterns = nativeBinding.extractShellPermissionPatterns
module.exports.isFileCommand = nativeBinding.isFileCommand
module.exports.isDangerousCommand = nativeBinding.isDangerousCommand
module.exports.assessBashRisk = nativeBinding.assessBashRisk
module.exports.assessFileRisk = nativeBinding.assessFileRisk
module.exports.getToolBaseRisk = nativeBinding.getToolBaseRisk
module.exports.checkRiskThreshold = nativeBinding.checkRiskThreshold
module.exports.parseRiskLevel = nativeBinding.parseRiskLevel

// Phase: Auto-Approve Engine
module.exports.AutoApproveEngineHandle = nativeBinding.AutoApproveEngineHandle
module.exports.createAutoApproveEngine = nativeBinding.createAutoApproveEngine
module.exports.createSafeOnlyEngine = nativeBinding.createSafeOnlyEngine
module.exports.createPermissiveEngine = nativeBinding.createPermissiveEngine
module.exports.evaluateAutoApprove = nativeBinding.evaluateAutoApprove
module.exports.evaluateAdaptiveAutoApprove = nativeBinding.evaluateAdaptiveAutoApprove
module.exports.canSafeAutoApprove = nativeBinding.canSafeAutoApprove

// Phase 8.1: Git Operations (native libgit2)
module.exports.GitOpsHandle = nativeBinding.GitOpsHandle
module.exports.openGitRepo = nativeBinding.openGitRepo
module.exports.initGitRepo = nativeBinding.initGitRepo
module.exports.cloneGitRepo = nativeBinding.cloneGitRepo
module.exports.isGitRepo = nativeBinding.isGitRepo

// Config Loader (JSONC parsing, config merging, schema validation)
module.exports.ConfigLoaderHandle = nativeBinding.ConfigLoaderHandle
module.exports.createConfigLoader = nativeBinding.createConfigLoader

// Phase: Compaction (context window management)
module.exports.CompactorHandle = nativeBinding.CompactorHandle
module.exports.createCompactor = nativeBinding.createCompactor
module.exports.createCompactorWithLimits = nativeBinding.createCompactorWithLimits

// Phase: File Watcher (native notify crate - replaces @parcel/watcher)
module.exports.FileWatcherHandle = nativeBinding.FileWatcherHandle
module.exports.createFileWatcher = nativeBinding.createFileWatcher
module.exports.createFileWatcherWithConfig = nativeBinding.createFileWatcherWithConfig
module.exports.watchPath = nativeBinding.watchPath
module.exports.WatchEventKind = nativeBinding.WatchEventKind

// Phase: Hook Pattern Matching (native regex with SIMD)
module.exports.PatternSetHandle = nativeBinding.PatternSetHandle
module.exports.createPatternSet = nativeBinding.createPatternSet
module.exports.scanPatterns = nativeBinding.scanPatterns
module.exports.scanContentPatterns = nativeBinding.scanContentPatterns
module.exports.matchesPattern = nativeBinding.matchesPattern
module.exports.containsPattern = nativeBinding.containsPattern

// Phase: Context Cache (project analysis caching)
module.exports.ContextCacheStoreHandle = nativeBinding.ContextCacheStoreHandle
module.exports.createMemoryContextCacheStore = nativeBinding.createMemoryContextCacheStore
module.exports.openContextCacheStore = nativeBinding.openContextCacheStore
module.exports.buildProjectCache = nativeBinding.buildProjectCache
module.exports.NapiCacheEntryType = nativeBinding.NapiCacheEntryType
module.exports.NapiComponentType = nativeBinding.NapiComponentType
module.exports.NapiRouteType = nativeBinding.NapiRouteType

// Extended token and fuzzy functions
module.exports.estimateTokensBatch = nativeBinding.estimateTokensBatch
module.exports.fitsTokenBudget = nativeBinding.fitsTokenBudget
module.exports.truncateToTokens = nativeBinding.truncateToTokens
module.exports.estimateChunkTokensNative = nativeBinding.estimateChunkTokensNative
module.exports.fuzzyFind = nativeBinding.fuzzyFind
module.exports.findBestFuzzyMatch = nativeBinding.findBestFuzzyMatch
module.exports.jaroSimilarity = nativeBinding.jaroSimilarity
module.exports.jaroWinklerSimilarity = nativeBinding.jaroWinklerSimilarity

// Phase 11: Markdown Parser
module.exports.parseMarkdown = nativeBinding.parseMarkdown
module.exports.extractMarkdownHeadings = nativeBinding.extractMarkdownHeadings
module.exports.extractMarkdownCodeBlocks = nativeBinding.extractMarkdownCodeBlocks
module.exports.extractMarkdownLinks = nativeBinding.extractMarkdownLinks
module.exports.extractMarkdownImages = nativeBinding.extractMarkdownImages
module.exports.renderMarkdownToHtml = nativeBinding.renderMarkdownToHtml
module.exports.extractMarkdownFrontmatter = nativeBinding.extractMarkdownFrontmatter
module.exports.stripMarkdownFrontmatter = nativeBinding.stripMarkdownFrontmatter

// Phase 12: PTY (native portable-pty)
module.exports.NapiPtyState = nativeBinding.NapiPtyState
module.exports.spawnPty = nativeBinding.spawnPty
module.exports.spawnPtyCommand = nativeBinding.spawnPtyCommand

// File edit and decision types
module.exports.FileEditType = nativeBinding.FileEditType
module.exports.DecisionType = nativeBinding.DecisionType
module.exports.AdrStatus = nativeBinding.AdrStatus
module.exports.FileStatusType = nativeBinding.FileStatusType
module.exports.NapiCompactionStrategy = nativeBinding.NapiCompactionStrategy
module.exports.NapiCommandRiskLevel = nativeBinding.NapiCommandRiskLevel
module.exports.RiskLevel = nativeBinding.RiskLevel
module.exports.AuthStatus = nativeBinding.AuthStatus

// Phase 10: File Ignore Engine
module.exports.IgnoreEngineHandle = nativeBinding.IgnoreEngineHandle
module.exports.createIgnoreEngine = nativeBinding.createIgnoreEngine
module.exports.createIgnoreEngineWithConfig = nativeBinding.createIgnoreEngineWithConfig
module.exports.shouldIgnorePath = nativeBinding.shouldIgnorePath
module.exports.filterIgnoredPaths = nativeBinding.filterIgnoredPaths
module.exports.filterPathsWithPatterns = nativeBinding.filterPathsWithPatterns
module.exports.getIgnoreDefaultFolders = nativeBinding.getIgnoreDefaultFolders
module.exports.getIgnoreDefaultPatterns = nativeBinding.getIgnoreDefaultPatterns

// Phase: Remote Policy (remote access control)
module.exports.RemotePolicyHandle = nativeBinding.RemotePolicyHandle
module.exports.getRemoteRiskLevel = nativeBinding.getRemoteRiskLevel
module.exports.isRemoteDangerous = nativeBinding.isRemoteDangerous
module.exports.isRemoteSafe = nativeBinding.isRemoteSafe
module.exports.shouldRequireRemoteApproval = nativeBinding.shouldRequireRemoteApproval
module.exports.RemoteRiskLevel = nativeBinding.RemoteRiskLevel

// Phase: Markdown Memory (dual-layer transparent memory)
module.exports.MarkdownMemoryHandle = nativeBinding.MarkdownMemoryHandle
module.exports.createMarkdownMemory = nativeBinding.createMarkdownMemory
module.exports.NapiMemoryCategory = nativeBinding.NapiMemoryCategory
module.exports.NapiDailyEntryType = nativeBinding.NapiDailyEntryType

// Phase: Memory System (unified memory management)
module.exports.MemorySystemHandle = nativeBinding.MemorySystemHandle
module.exports.createMemorySystem = nativeBinding.createMemorySystem
module.exports.createMemoryObservabilityStore = nativeBinding.createMemoryObservabilityStore

// Phase: Safety Guardrails (loop detection, state tracking)
module.exports.SafetyGuardrailsHandle = nativeBinding.SafetyGuardrailsHandle
module.exports.createSafetyGuardrails = nativeBinding.createSafetyGuardrails
module.exports.NapiToolResult = nativeBinding.NapiToolResult

// Phase: CLOSE Decision Framework
module.exports.evaluateClose = nativeBinding.evaluateClose

// Phase: Embedding Index (SIMD-accelerated KNN search)
module.exports.EmbeddingIndexHandle = nativeBinding.EmbeddingIndexHandle
module.exports.createEmbeddingIndex = nativeBinding.createEmbeddingIndex

// Phase: Skill Parser
module.exports.parseSkillContent = nativeBinding.parseSkillContent
module.exports.parseSkillFromFile = nativeBinding.parseSkillFromFile
module.exports.parseSkillMetadataOnly = nativeBinding.parseSkillMetadataOnly
module.exports.validateSkillContent = nativeBinding.validateSkillContent
module.exports.parseSkillsBatch = nativeBinding.parseSkillsBatch
module.exports.extractSkillFrontmatter = nativeBinding.extractSkillFrontmatter
module.exports.stripSkillFrontmatter = nativeBinding.stripSkillFrontmatter

// Phase: Truncation
module.exports.TruncatorHandle = nativeBinding.TruncatorHandle
module.exports.truncateOutput = nativeBinding.truncateOutput
module.exports.truncatePreview = nativeBinding.truncatePreview

// Phase: Read (native file reading)
module.exports.ReaderHandle = nativeBinding.ReaderHandle
module.exports.readFileWithLines = nativeBinding.readFileWithLines
module.exports.readFileRange = nativeBinding.readFileRange
module.exports.isBinaryFile = nativeBinding.isBinaryFile
module.exports.countFileLines = nativeBinding.countFileLines

// Phase: Dependency Analysis
module.exports.extractFileDependencies = nativeBinding.extractFileDependencies
module.exports.extractDirectoryDependencies = nativeBinding.extractDirectoryDependencies
