// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent switch event data.
 */
export type AgentSwitchData = { 
/**
 * Previous agent.
 */
from: string, 
/**
 * New agent.
 */
to: string, 
/**
 * Reason for switch.
 */
reason?: string | null, };
