// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Debug info event data.
 */
export type DebugInfoData = { 
/**
 * Model name.
 */
model?: string | null, 
/**
 * Provider name.
 */
provider?: string | null, 
/**
 * Input tokens.
 */
input_tokens?: bigint | null, 
/**
 * Output tokens.
 */
output_tokens?: bigint | null, 
/**
 * Total tokens.
 */
total_tokens?: bigint | null, 
/**
 * Duration in milliseconds.
 */
duration_ms?: bigint | null, 
/**
 * Request bytes.
 */
request_bytes?: bigint | null, 
/**
 * Response bytes.
 */
response_bytes?: bigint | null, };
