// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Heartbeat event data.
 */
export type HeartbeatData = { 
/**
 * Current stage.
 */
stage?: string | null, 
/**
 * Elapsed time in milliseconds.
 */
elapsed_ms: bigint, };
