// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output event data.
 */
export type OutputData = { 
/**
 * Output content.
 */
content: string, 
/**
 * Whether this is a partial output (streaming).
 */
is_partial: boolean, };
