// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event data.
 */
export type ProgressData = { 
/**
 * Current stage.
 */
stage: string, 
/**
 * Progress message.
 */
message: string, 
/**
 * Percentage (0-100).
 */
percentage?: number | null, };
