// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Skill use event data.
 */
export type SkillUseData = { 
/**
 * Skill name.
 */
skill: string, 
/**
 * Skill arguments.
 */
args?: string | null, 
/**
 * Duration in milliseconds.
 */
duration_ms?: bigint | null, };
