// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskUsage } from "./TaskUsage";

/**
 * Task completed event data.
 */
export type TaskCompletedData = { 
/**
 * Final output.
 */
output: string, 
/**
 * Summary (optional).
 */
summary?: string | null, 
/**
 * Token usage.
 */
usage?: TaskUsage | null, };
