// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage statistics.
 */
export type TaskUsage = { 
/**
 * Input tokens.
 */
input_tokens: bigint, 
/**
 * Output tokens.
 */
output_tokens: bigint, 
/**
 * Total duration in milliseconds.
 */
duration_ms: bigint, };
