// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task started event data.
 */
export type TaskStartedData = { 
/**
 * Agent executing the task.
 */
agent: string, 
/**
 * Session ID.
 */
session_id: string, 
/**
 * Trace ID.
 */
trace_id: string, };
