// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Task created event data.
 */
export type TaskCreatedData = { 
/**
 * Task ID.
 */
task_id: string, 
/**
 * User ID.
 */
user_id: string, 
/**
 * Channel type (telegram, discord, etc.).
 */
channel: string, 
/**
 * Channel/chat ID.
 */
channel_id: string, 
/**
 * User prompt.
 */
prompt: string, 
/**
 * Agent name.
 */
agent: string, 
/**
 * Trace ID for distributed tracing.
 */
trace_id: string, 
/**
 * Message history for context.
 */
chat_history: Array<JsonValue>, };
