// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * Task state projection (materialized from events).
 *
 * This is stored in Redis Hash for quick access.
 */
export type TaskState = { 
/**
 * Task ID.
 */
task_id: string, 
/**
 * Current status.
 */
status: TaskStatus, 
/**
 * Current agent.
 */
current_agent: string | null, 
/**
 * Progress percentage (0-100).
 */
progress_pct: number, 
/**
 * Last event sequence number.
 */
last_event_seq: bigint, 
/**
 * Partial output buffer.
 */
output_buffer?: string | null, 
/**
 * Task start time.
 */
started_at?: string | null, 
/**
 * Last update time.
 */
updated_at: string, 
/**
 * Last heartbeat time.
 */
last_heartbeat?: string | null, 
/**
 * Error message (if failed).
 */
error?: string | null, };
