// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task failed event data.
 */
export type TaskFailedData = { 
/**
 * Error message.
 */
error: string, 
/**
 * Whether the task can be recovered.
 */
recoverable: boolean, 
/**
 * Error code (for categorization).
 */
code?: string | null, };
