// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task status values.
 */
export type TaskStatus = "pending" | "running" | "awaiting_approval" | "completed" | "failed";
