// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfoData } from "./AgentInfoData";
import type { AgentSwitchData } from "./AgentSwitchData";
import type { ConfirmationData } from "./ConfirmationData";
import type { DebugInfoData } from "./DebugInfoData";
import type { HeartbeatData } from "./HeartbeatData";
import type { OutputData } from "./OutputData";
import type { ProgressData } from "./ProgressData";
import type { SkillUseData } from "./SkillUseData";
import type { TaskCompletedData } from "./TaskCompletedData";
import type { TaskCreatedData } from "./TaskCreatedData";
import type { TaskFailedData } from "./TaskFailedData";
import type { TaskStartedData } from "./TaskStartedData";
import type { ThoughtData } from "./ThoughtData";
import type { ToolUseData } from "./ToolUseData";

/**
 * All task event types.
 */
export type TaskEvent = { "type": "task_created" } & TaskCreatedData | { "type": "task_started" } & TaskStartedData | { "type": "thought" } & ThoughtData | { "type": "tool_use" } & ToolUseData | { "type": "progress" } & ProgressData | { "type": "output" } & OutputData | { "type": "confirmation" } & ConfirmationData | { "type": "agent_switch" } & AgentSwitchData | { "type": "heartbeat" } & HeartbeatData | { "type": "debug_info" } & DebugInfoData | { "type": "agent_info" } & AgentInfoData | { "type": "skill_use" } & SkillUseData | { "type": "task_completed" } & TaskCompletedData | { "type": "task_failed" } & TaskFailedData;
