// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Thought event data.
 */
export type ThoughtData = { 
/**
 * Thought content.
 */
content: string, };
