// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Tool use event data.
 */
export type ToolUseData = { 
/**
 * Tool name.
 */
tool: string, 
/**
 * Tool arguments.
 */
args: JsonValue, 
/**
 * Tool result (if completed).
 */
result?: JsonValue | null, 
/**
 * Duration in milliseconds.
 */
duration_ms?: bigint | null, 
/**
 * Whether this is a result tool (vs intermediate).
 */
is_result_tool: boolean, };
