// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ActionCategory } from "./ActionCategory";

/**
 * An action to be evaluated by guardrails.
 */
export type Action = { 
/**
 * Unique action ID
 */
id: string, 
/**
 * Action category
 */
category: ActionCategory, 
/**
 * Specific action type (e.g., "purchase", "delete", "execute")
 */
action_type: string, 
/**
 * Human-readable description
 */
description: string, 
/**
 * Source hand/agent ID
 */
source_id: string, 
/**
 * Optional monetary amount (USD)
 */
amount: number | null, 
/**
 * Optional target (URL, file path, etc.)
 */
target: string | null, 
/**
 * Additional metadata
 */
metadata: { [key in string]: JsonValue }, 
/**
 * Timestamp
 */
created_at: string, };
