// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { ApprovalStatus } from "./ApprovalStatus";
import type { RiskLevel } from "./RiskLevel";

/**
 * An approval request waiting for user confirmation.
 */
export type ApprovalRequest = { 
/**
 * Unique approval ID
 */
id: string, 
/**
 * The action being approved
 */
action: Action, 
/**
 * Risk level of the action
 */
risk_level: RiskLevel, 
/**
 * When the request was created
 */
created_at: string, 
/**
 * When the request expires
 */
expires_at: string, 
/**
 * Current status
 */
status: ApprovalStatus, 
/**
 * User who approved/denied (if resolved)
 */
resolved_by: string | null, 
/**
 * Resolution timestamp
 */
resolved_at: string | null, 
/**
 * Optional notes from resolver
 */
notes: string | null, };
