// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk level for an action.
 */
export type RiskLevel = "safe" | "low" | "medium" | "high" | "critical";
