// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskLevel } from "./RiskLevel";

/**
 * Type of operation requiring approval.
 */
export type ApprovalType = { "type": "merge_request", platform: string, repo: string, mr_id: bigint, } | { "type": "trading_command", asset: string, action: string, amount: number, } | { "type": "config_change", key: string, old_value: string, new_value: string, } | { "type": "high_cost_operation", operation: string, estimated_cost: number, } | { "type": "risk_operation", description: string, risk_level: RiskLevel, };
