// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalRequest } from "./ApprovalRequest";

/**
 * Response after creating or retrieving an approval.
 */
export type ApprovalResponse = { 
/**
 * Whether the operation succeeded
 */
success: boolean, 
/**
 * The approval request (if successful)
 */
approval: ApprovalRequest | null, 
/**
 * Error message (if failed)
 */
error: string | null, };
